'use client';
import { useEffect, useState } from 'react';
import { Ld } from '@axp/design-system/ledger';
import { CampaignEditor } from './CampaignEditor';
import { amount, api, campaignRows, count, date, decimal, type Bootstrap, type Campaign, type ProductState } from './model';
type View = 'campaigns' | 'account' | 'editor' | 'detail';
const statusLabel = (status: string) => status === 'active' ? 'Active' : status === 'paused' ? 'Paused' : status === 'settled' ? 'Settled' : 'Draft';
function Status({ status }: { status: string }) { return <Ld.Tag tone={status === 'active' ? 'success' : status === 'paused' ? 'warning' : 'outline'} dot={status === 'active'}>{statusLabel(status)}</Ld.Tag>; }
export function AdvertiserDashboard() {
  const [bootstrap, setBootstrap] = useState<Bootstrap | null>(null), [state, setState] = useState<ProductState | null>(null);
  const [demoMode, setDemoMode] = useState(false);
  const [editorDirty, setEditorDirty] = useState(false);
  const [view, setView] = useState<View>('campaigns'), [selected, setSelected] = useState<string | null>(null), [editing, setEditing] = useState<Campaign | undefined>();
  const [error, setError] = useState(''), [message, setMessage] = useState(''), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false);
  const [query, setQuery] = useState(''), [filter, setFilter] = useState('all');
  const [accountName, setAccountName] = useState(''), [accountURL, setAccountURL] = useState(''), [accountErrors, setAccountErrors] = useState<Record<string, string>>({});
  async function refresh() { const next = await api<ProductState>('/state'); setState(next); return next; }
  async function load() {
    setLoading(true); setError('');
    try { const [b, s] = await Promise.all([api<Bootstrap>('/bootstrap'), api<ProductState>('/state')]); setBootstrap(b); setDemoMode(b.demo?.enabled ?? false); setState(s); setAccountName(s.account?.name ?? ''); setAccountURL(s.account?.websiteURL ?? ''); }
    catch (e) { setError(e instanceof Error ? e.message : 'The workspace could not be loaded.'); }
    finally { setLoading(false); }
  }
  useEffect(() => { void load(); }, []);
  useEffect(() => {
    const update = () => { if (document.visibilityState === 'visible' && state && view !== 'editor') void refresh().catch(() => {}); };
    window.addEventListener('focus', update); document.addEventListener('visibilitychange', update);
    const timer = setInterval(update, 15000);
    return () => { window.removeEventListener('focus', update); document.removeEventListener('visibilitychange', update); clearInterval(timer); };
  }, [Boolean(state), view]);
  async function saveAccount() {
    const e: Record<string, string> = {};
    if (!accountName.trim()) e.name = 'Enter your business or workspace name.';
    try { const u = new URL(accountURL); if (u.protocol !== 'https:' || u.username || u.password) throw new Error(); } catch { e.url = 'Use a complete https website URL with no embedded credentials.'; }
    setAccountErrors(e); if (Object.keys(e).length) return;
    setBusy(true); setError('');
    try { await api('/account', bootstrap?.csrf, { name: accountName.trim(), websiteURL: accountURL.trim() }); await refresh(); setMessage('Account saved. Your workspace is ready.'); setView('campaigns'); }
    catch (err) { setError(err instanceof Error ? err.message : 'Could not save account.'); }
    finally { setBusy(false); }
  }
  const rows = state ? campaignRows(state) : [], current = rows.find(c => c.id === selected);
  function open(c: Campaign) { setError(''); setMessage(''); if (c.status === 'draft') { setEditing(c); setView('editor'); } else { setSelected(c.id); setView('detail'); } }
  function create() { setEditing(undefined); setMessage(''); setError(''); setView('editor'); }
  async function action(c: Campaign, verb: 'pause' | 'resume' | 'duplicate' | 'settle') {
    setBusy(true); setError(''); setMessage('');
    try {
      const result = await api<{ campaign: Campaign }>(`/campaigns/${encodeURIComponent(c.id)}/${verb}`, bootstrap?.csrf, {}); await refresh();
      if (verb === 'duplicate') { setEditing(result.campaign); setView('editor'); }
      else setMessage(verb === 'settle' ? 'Synthetic settlement recorded. Campaign is closed.' : verb === 'pause' ? 'Campaign paused. New opportunities will exclude it.' : 'Campaign resumed. It can compete again.');
    } catch (e) { setError(e instanceof Error ? e.message : 'The action could not be completed.'); }
    finally { setBusy(false); }
  }
  const active = rows.filter(c => c.status === 'active').length;
  const activeAdvertisers = new Set(rows.filter(c => c.status === 'active').map(c => c.advertiserId ?? `${c.brandName.toLowerCase()}|${c.websiteURL}`)).size;
  const advertiserCount = state?.advertisers?.length ?? new Set(rows.map(c => c.advertiserId ?? `${c.brandName.toLowerCase()}|${c.websiteURL}`)).size;
  const visible = rows.filter(c => (filter === 'all' || c.status === filter) && `${c.name} ${c.brandName}`.toLowerCase().includes(query.toLowerCase()));
  const sum = (key: 'spend' | 'settled' | 'remaining') => rows.reduce((total, c) => total + BigInt(amount(c, key)), 0n).toString();
  const summary = state?.summary;
  const nav = (href: string, label: string, current: boolean, meta?: string) => ({ href, label, current, meta });
  return <div className="ad-dashboard"><Ld.Shell top={<Ld.TopBar brand={<Ld.Wordmark href="/" />} run={<span className="ad-workspace-name">{state?.account?.name ?? 'Advertiser workspace'}</span>} chips={<Ld.Tag tone="outline">Synthetic test credits</Ld.Tag>} actions={<Ld.Button variant="secondary" href="/publisher-demo/">Open publisher demo →</Ld.Button>} />} side={<>
    <Ld.SideNav groups={[{ label: 'Workspace', items: [nav('#campaigns', 'Campaigns', view !== 'account', String(rows.length)), nav('#account', 'Workspace settings', view === 'account')] }, { label: 'Test your campaign', items: [nav('/publisher-demo/', 'Publisher demo →', false)] }]} foot={<><strong>Synthetic mode</strong><p>No bank funding or real token transfers.</p></>} Link={({ href, children, className, ...rest }) => <a {...rest} href={href} className={className} onClick={e => { if (href === '#campaigns' || href === '#account') { e.preventDefault(); if (view === 'editor' && editorDirty && !window.confirm('Leave this editor? Unsaved changes will be lost. Save your draft first to keep them.')) return; setView(href === '#account' ? 'account' : 'campaigns'); setError(''); setMessage(''); } }}>{children}</a>} />
    </>}>
    {error && <div className="ad-global-message" role="alert"><Ld.Callout tone="danger" title="Could not complete the request">{error}</Ld.Callout></div>}
    {state && <div className="ad-demo-controls"><label className="ad-demo-switch"><input type="checkbox" role="switch" checked={demoMode} onChange={event => setDemoMode(event.target.checked)} /><span>Demo autofill</span><Ld.Tag tone="outline">Optional</Ld.Tag></label><span className="ld-caption">{demoMode ? 'Tab in an empty setup field fills the current step with editable HarborKey suggestions.' : 'Enable keyboard suggestions to create HarborKey for the presentation.'}</span></div>}
    {message && <div className="ad-global-message" role="status"><Ld.Callout tone="brand">{message}</Ld.Callout></div>}
    {loading ? <Ld.Empty title="Loading your workspace">Fetching saved campaigns and delivery records.</Ld.Empty> : !state || !bootstrap ? <Ld.Empty title="Your workspace is unavailable" action={<Ld.Button onClick={() => void load()}>Try again</Ld.Button>}>Check that the product API is running, then retry.</Ld.Empty> : <>
    {!state.account || view === 'account' ? <>
      <Ld.PageBar title={state.account ? 'Workspace settings' : 'Set up your advertiser workspace'} sub={state.account ? 'One workspace can manage multiple advertisers and campaigns.' : 'Create a workspace, then add an advertiser and launch its first campaign.'} />
      <div className="ad-account-grid"><Ld.Panel title={state.account ? 'Business details' : 'Start with your business'}><form onSubmit={e => { e.preventDefault(); void saveAccount(); }} noValidate className="ad-form-fields"><Ld.Field label="Business or workspace name" error={accountErrors.name}><input className="ld-input" autoComplete="organization" value={accountName} onChange={e => setAccountName(e.target.value)} maxLength={120} aria-invalid={Boolean(accountErrors.name)} /></Ld.Field><Ld.Field label="Business website" hint="Include https://. You can choose a different destination for each campaign." error={accountErrors.url}><input type="url" className="ld-input" autoComplete="url" value={accountURL} onChange={e => setAccountURL(e.target.value)} maxLength={500} aria-invalid={Boolean(accountErrors.url)} /></Ld.Field><div><Ld.Button type="submit" disabled={busy}>{busy ? 'Saving…' : state.account ? 'Save account' : 'Create account →'}</Ld.Button></div></form></Ld.Panel><div className="ad-onboarding-note"><span className="ad-large-number">A useful offer.<br />A relevant moment.</span><p>Your campaign competes for a disclosed Sponsored card in a participating AI app.</p><ol><li>Describe your offer and relevant contexts.</li><li>Approve the exact card and set limits.</li><li>Launch and try it in the publisher demo.</li></ol><Ld.Callout title="A workspace you can use" tone="brand">Campaigns and drafts are saved on the backend. This release uses synthetic test credits.</Ld.Callout></div></div>
    </> : view === 'editor' ? <CampaignEditor demoMode={demoMode} key={editing?.id ?? 'new'} initial={editing} bootstrap={bootstrap} account={state.account} onDirtyChange={setEditorDirty} onSaved={async () => { await refresh(); }} onClose={() => setView('campaigns')} onLaunched={id => { setSelected(id); setView('detail'); setMessage('Campaign launched. Open the publisher demo to create a matching conversation.'); }} /> : view === 'detail' && current ? <>
      <Ld.PageBar title={current.name} sub={current.brandName} meta={<Status status={current.status} />} crumbs={<button className="ad-text-button" onClick={() => setView('campaigns')}>← Campaigns</button>} actions={<div className="ad-action-row">{current.status === 'active' ? <Ld.Button variant="secondary" disabled={busy} onClick={() => void action(current, 'pause')}>Pause campaign</Ld.Button> : current.status === 'paused' ? <Ld.Button disabled={busy} onClick={() => void action(current, 'resume')}>Resume campaign</Ld.Button> : null}<Ld.Button variant="ghost" disabled={busy} onClick={() => void action(current, 'duplicate')}>Duplicate</Ld.Button></div>} />
      <div className="ad-kpis"><Ld.Kpi label="Accepted deliveries" value={count(current, state.deliveries)} context="Sponsored cards inserted by a publisher" /><Ld.Kpi label="Campaign spend" value={decimal(amount(current, 'spend'))} unit="test credits" context="Accepted delivery charges" /><Ld.Kpi label="Remaining cap" value={decimal(amount(current, 'remaining'))} unit="test credits" context={`Of ${decimal(current.budgetCapBaseUnits)} allocated cap`} /><Ld.Kpi label="Settled" value={decimal(amount(current, 'settled'))} unit="test credits" context="Synthetic ledger settlement" /></div>
      {current.status === 'active' && <Ld.Callout title="See your campaign in a conversation" tone="brand" actions={<Ld.Button href="/publisher-demo/">Open publisher demo →</Ld.Button>}>Ask a question related to your contexts. Your campaign competes under its capabilities and spend limits.</Ld.Callout>}
      <div className="ad-money-states"><Ld.Stat label="Available cap" value={`${decimal(amount(current, 'remaining'))} test credits`} caption="Cap less accepted charges and reserved awards" /><Ld.Stat label="Reserved" value={`${decimal(current.reservedBaseUnits)} test credits`} caption="Awaiting delivery, not yet a charge" /><Ld.Stat label="Accepted" value={`${decimal(current.acceptedBaseUnits)} test credits`} caption="Already counted in campaign spend" /><Ld.Stat label="Authorized" value={`${decimal(current.authorizedBaseUnits)} test credits`} caption="Cumulative, does not add spend" /><Ld.Stat label="Settled" value={`${decimal(current.settledBaseUnits)} test credits`} caption="Synthetic payment ledger" /><Ld.Stat label="Refund" value={`${decimal(current.refundBaseUnits)} test credits`} caption="Unused allocation returned at close" /></div>
      <div className="ad-detail-grid"><div className="ld-stack"><Ld.Panel title="Delivery records" sub="Insertion is the purchased event. It does not prove human attention." flush>{state.deliveries.filter(d => d.campaignId === current.id).length ? <Ld.Table rows={state.deliveries.filter(d => d.campaignId === current.id)} caption="Accepted campaign deliveries" columns={[{ key: 'question', head: 'Conversation', cell: d => <span className="ad-delivery-question">{d.question ?? 'Publisher Sponsored card'}</span> }, { key: 'time', head: 'Recorded', cell: d => date(d.createdAt) }, { key: 'amount', head: 'Charge · test credits', num: true, cell: d => decimal(d.priceBaseUnits ?? d.amountBaseUnits ?? '0') }]} /> : <Ld.Empty title="No accepted deliveries yet" action={<Ld.Button variant="secondary" href="/publisher-demo/">Try a matching question →</Ld.Button>}>Launch an eligible campaign and insert its Sponsored card in the publisher demo to create a delivery record.</Ld.Empty>}</Ld.Panel>
      <Ld.Panel title="Context and spending"><dl className="ad-review"><div><dt>Conversation contexts</dt><dd>{current.contextHints.join(' · ')}</dd></div><div><dt>Declared capabilities</dt><dd>{current.declaredCapabilities.map(id => bootstrap.capabilities.find(cap => cap.id === id)?.label ?? id).join(', ') || 'None declared'}</dd></div><div><dt>Maximum bid</dt><dd>{decimal(current.maxBidBaseUnits)} test credits / card</dd></div><div><dt>Total campaign cap</dt><dd>{decimal(current.budgetCapBaseUnits)} test credits</dd></div><div><dt>Test-credit allocation</dt><dd>{decimal(current.depositBaseUnits)} test credits</dd></div></dl></Ld.Panel>
      <Ld.Panel title="Recent activity">{state.events.filter(e => e.campaignId === current.id).length ? <Ld.Timeline rows={state.events.filter(e => e.campaignId === current.id).slice(-8).reverse().map((e, i) => ({ key: e.id ?? String(i), time: date(e.createdAt), what: e.message ?? e.type?.replaceAll('_', ' ') ?? 'Campaign updated' }))} /> : <p className="ld-secondary">Activity will appear as this campaign is operated.</p>}</Ld.Panel></div>
      <aside className="ld-stack"><Ld.Panel title="Approved Sponsored card"><Ld.SponsoredCard advertiser={current.brandName} text={current.approvedText} url={current.websiteURL} /><p className="ad-card-caption ld-caption">Destination: {current.websiteURL}</p></Ld.Panel><Ld.Panel title="Synthetic settlement" sub="Test ledger only"><p className="ld-secondary">Close this campaign and record accepted charges as settled. Closing ends new competition for this campaign.</p><dl className="ad-review"><div><dt>Authorized</dt><dd>{decimal(current.authorizedBaseUnits)} test credits</dd></div><div><dt>Settled</dt><dd>{decimal(current.settledBaseUnits)} test credits</dd></div></dl><Ld.Button variant="secondary" disabled={busy || current.status === 'settled'} onClick={() => void action(current, 'settle')}>{current.status === 'settled' ? 'Closed and settled' : 'Close and settle test credits'}</Ld.Button><p className="ad-card-caption ld-caption">No blockchain transaction or real USDC transfer.</p></Ld.Panel></aside></div>
    </> : <>
      <Ld.PageBar title="Campaigns" sub="Manage distinct advertisers and bring their offers to relevant conversations." actions={<Ld.Button size="lg" onClick={create}>Create advertiser & campaign</Ld.Button>} />
      <div className="ad-mode-note"><span className="ld-label">Synthetic test-credit mode</span><span>Saved campaigns, accepted delivery records, simulated settlement.</span></div>
      <div className="ad-engine-note"><Ld.Tag tone={bootstrap.engine?.ready ? 'brand' : 'warning'}>{bootstrap.engine?.ready ? 'Buying decisions with Jev' : 'Jev unavailable'}</Ld.Tag><span className="ld-caption">{bootstrap.engine?.ready ? 'Your advertiser context hints guide the buying agent. Preview checks do not call the model.' : bootstrap.engine?.reason ?? 'Model readiness is checked by the backend.'}</span></div>
      <div className="ad-kpis"><Ld.Kpi label="Active advertisers" value={activeAdvertisers} context={`${active} active campaigns · ${rows.filter(c => c.status === 'draft').length} drafts`} /><Ld.Kpi label="Accepted deliveries" value={summary?.deliveryCount ?? state.deliveries.length} context="Cards inserted by a publisher" /><Ld.Kpi label="Campaign spend" value={decimal(summary?.spendBaseUnits ?? sum('spend'))} unit="test credits" context="Accepted delivery charges" /><Ld.Kpi label="Settled" value={decimal(summary?.settledBaseUnits ?? sum('settled'))} unit="test credits" context="Synthetic ledger only" /></div>
      {!rows.length ? <div className="ad-empty-grid"><Ld.Panel><Ld.Empty title="Your first campaign starts here" action={<Ld.Button onClick={create}>Create advertiser & campaign →</Ld.Button>}>Describe your offer, choose relevant contexts, approve your Sponsored card and set a clear spending cap.</Ld.Empty></Ld.Panel><Ld.Panel title="What you are buying"><div className="ad-example-card"><Ld.SponsoredCard advertiser="Your brand" text="A useful offer, shown as a clearly disclosed card beneath an independent AI answer." url="" /></div><p className="ld-secondary ad-card-caption">You pay for accepted card insertion. Human attention and advertising effectiveness are not measured here.</p></Ld.Panel></div> : <Ld.Panel title="Advertisers and campaigns" sub={`${advertiserCount} distinct advertisers in this workspace. Drafts stay saved until launch.`} actions={<Ld.Button variant="ghost" disabled={busy} onClick={async () => { setBusy(true); try { await refresh(); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Refresh failed.'); } finally { setBusy(false); } }}>Refresh</Ld.Button>} flush><div className="ad-table-tools"><div className="ad-status-filters" role="group" aria-label="Filter by campaign status">{[['all', 'All campaigns'], ['active', 'Active'], ['draft', 'Drafts'], ['paused', 'Paused'], ['settled', 'Settled']].map(([value, label]) => <button key={value} type="button" aria-pressed={filter === value} onClick={() => setFilter(value)}>{label}</button>)}</div><input className="ld-input ad-search" aria-label="Search campaigns" placeholder="Search campaigns" value={query} onChange={e => setQuery(e.target.value)} /></div>{visible.length ? <Ld.Table rows={visible} caption="Saved advertiser campaigns" columns={[{ key: 'name', head: 'Advertiser & campaign', cell: c => <button className="ad-campaign-link" onClick={() => open(c)}><span className="ad-initial" aria-hidden="true">{(c.brandName || c.name || 'C').slice(0, 1).toUpperCase()}</span><span><strong>{c.brandName || 'Brand not added'}</strong><small>{c.name || 'Untitled campaign'}</small></span></button> }, { key: 'status', head: 'Status', cell: c => <Status status={c.status} /> }, { key: 'deliveries', head: 'Deliveries', num: true, cell: c => count(c, state.deliveries) }, { key: 'spend', head: 'Spend · test credits', num: true, cell: c => decimal(amount(c, 'spend')) }, { key: 'cap', head: 'Cap · test credits', num: true, cell: c => decimal(c.budgetCapBaseUnits) }, { key: 'open', head: '', cell: c => <Ld.Button variant="ghost" size="sm" onClick={() => open(c)}>{c.status === 'draft' ? 'Continue →' : 'View →'}</Ld.Button> }]} /> : <Ld.Empty title="No campaigns match">Choose another status or clear your search.</Ld.Empty>}</Ld.Panel>}
      <div className="ad-bottom-note"><span>Delivery means accepted Sponsored card insertion, not human attention.</span><a href="/publisher-demo/">Test in the publisher demo →</a></div>
    </>}
    </>}
  </Ld.Shell></div>;
}
