import { Ld } from '@axp/design-system/ledger';
import { date, decimal, type Campaign } from './model';
import { canRetryOpening, currencyUnit, nativeSettlementLabel, paymentActions, paymentPhase, phaseLabel, transactionURL } from './payment';

export function PaymentPanel({ campaign, native, busy, onSettle, onReconcile, onAuthorize, onRetryOpen }: { campaign: Campaign; native: boolean; busy: boolean; onSettle: () => void; onReconcile: () => void; onAuthorize: () => void; onRetryOpen: () => void }) {
  const payment = campaign.payment, phase = paymentPhase(campaign), unit = currencyUnit(native);
  const reason = campaign.paymentError ?? payment?.error ?? payment?.reason;
  const {closed, pending, uncertain, authorize, settle, reconcile} = paymentActions(campaign);
  return <Ld.Panel title={native ? 'Devnet payment channel' : 'Synthetic settlement'} sub={native ? 'Test USDC · Solana Devnet' : 'Test ledger only'}>
    {native ? <>
      <div className="ad-payment-status" role="status"><Ld.Tag tone={uncertain ? 'warning' : closed ? 'success' : 'outline'}>{phaseLabel(phase)}</Ld.Tag></div>
      <p className="ld-secondary">Closing stops new awards, resolves outstanding deliveries, pays accepted charges to the publisher and returns the unused deposit. Final amounts appear after confirmation.</p>
      {reason && <Ld.Callout tone="warning" title="Payment needs attention">{reason.replaceAll('_', ' ')}</Ld.Callout>}
      {canRetryOpening(campaign) && <p className="ld-caption">Retry checks current status and reuses this saved campaign and channel. It never creates a replacement deposit.</p>}
      {pending && <p className="ld-caption">The saved operation is in progress. Refresh or reconcile its status; no new deposit is needed.</p>}
      {uncertain && <p className="ld-caption">An uncertain result does not prove failure or refund. Reconcile the saved identity before taking another payment action.</p>}
      <dl className="ad-review"><div><dt>Channel</dt><dd className="ad-payment-identity">{payment?.address ?? payment?.protocolChannelId ?? payment?.channelId ?? 'Not opened'}</dd></div><div><dt>Confirmed deposit</dt><dd>{payment?.confirmedDepositBaseUnits === undefined ? 'Awaiting confirmation' : `${decimal(payment.confirmedDepositBaseUnits)} ${unit}`}</dd></div><div><dt>Accepted charges</dt><dd>{decimal(campaign.acceptedBaseUnits)} {unit}</dd></div><div><dt>Cumulative authorized</dt><dd>{decimal(campaign.authorizedBaseUnits)} {unit}</dd></div><div><dt>Publisher payout</dt><dd>{nativeSettlementLabel(campaign, "settledBaseUnits")}</dd></div><div><dt>Returned deposit</dt><dd>{nativeSettlementLabel(campaign, "refundBaseUnits")}</dd></div></dl>
      <div className="ad-action-row">{canRetryOpening(campaign) && <Ld.Button variant="secondary" disabled={busy} onClick={onRetryOpen}>Retry saved channel opening</Ld.Button>}{authorize && <Ld.Button variant="secondary" disabled={busy} onClick={onAuthorize}>Authorize accepted deliveries</Ld.Button>}<Ld.Button variant="secondary" disabled={busy || closed || !settle} onClick={onSettle}>{busy ? 'Processing…' : closed ? 'Closed and settled' : 'Close & settle Test USDC'}</Ld.Button>{reconcile && <Ld.Button variant="ghost" disabled={busy} onClick={onReconcile}>Reconcile status</Ld.Button>}</div>
      <div className="ad-payment-evidence"><span className="ld-label">Transactions</span>{payment?.transactions?.length ? <ul>{payment.transactions.map((tx, i) => {
        const url = transactionURL(tx.signature);
        return <li key={`${tx.operation}-${tx.signature ?? i}`}><div><strong>{tx.operation.replaceAll('_', ' ')}</strong><span className="ld-caption">{tx.status.replaceAll('_', ' ')}{tx.finality ? ` · ${tx.finality}` : ''}{tx.createdAt ? ` · ${date(tx.createdAt)}` : ''}</span></div>{url ? <a href={url} target="_blank" rel="noopener noreferrer">View on Devnet ↗</a> : <span className="ld-caption">No transaction signature</span>}<dl className="ad-transaction-deltas">{tx.networkFeeLamports !== undefined && <div><dt>Network fee</dt><dd>{tx.networkFeeLamports} lamports</dd></div>}{tx.newRentLamports !== undefined && <div><dt>New rent</dt><dd>{tx.newRentLamports} lamports</dd></div>}{tx.reclaimedRentLamports !== undefined && <div><dt>Reclaimed rent</dt><dd>{tx.reclaimedRentLamports} lamports</dd></div>}{tx.tokenDeltas && <div><dt>Test USDC deltas · base units</dt><dd>Payer {tx.tokenDeltas.payer ?? "unavailable"} · publisher {tx.tokenDeltas.publisher ?? "unavailable"} · treasury {tx.tokenDeltas.treasury ?? "unavailable"}</dd></div>}</dl></li>;
      })}</ul> : <p className="ld-caption">Transaction evidence will appear when a native operation is recorded.</p>}</div>
      {payment?.vouchers?.length ? <div className="ad-payment-evidence"><span className="ld-label">Cumulative authorizations</span><ul>{payment.vouchers.map(v => <li key={v.chargeId}><div><strong>Charge {v.sequence} · {v.status.replaceAll("_", " ")}</strong><span className="ld-caption">Increment {decimal(v.incrementBaseUnits)} {unit} · cumulative {decimal(v.cumulativeAmountBaseUnits)} {unit}</span><span className="ld-caption ad-payment-identity">{v.chargeId}</span></div></li>)}</ul></div> : null}
      <p className="ad-card-caption ld-caption">Accepted charges count once. Authorization and settlement do not add spend. Devnet SOL fees and rent are separate.</p>
    </> : <>
      <p className="ld-secondary">Close this campaign and record accepted charges as settled. Closing ends new competition for this campaign.</p><dl className="ad-review"><div><dt>Authorized</dt><dd>{decimal(campaign.authorizedBaseUnits)} {unit}</dd></div><div><dt>Settled</dt><dd>{decimal(campaign.settledBaseUnits)} {unit}</dd></div></dl><Ld.Button variant="secondary" disabled={busy || closed} onClick={onSettle}>{closed ? 'Closed and settled' : 'Close and settle test credits'}</Ld.Button><p className="ad-card-caption ld-caption">No blockchain transaction or real USDC transfer.</p>
    </>}
  </Ld.Panel>;
}
