import type {FinancialMetadata, NativePayment} from '../../../../../packages/publisher-sdk/financial.mjs';
export {financialModeOf, moneyUnit} from '../../../../../packages/publisher-sdk/financial.mjs';
import type {OpportunityInput, OpportunityResult, ReceiptResult, RenderObservation} from '../../../../../packages/publisher-sdk/index.mjs';
export type Engine = {id?: string; execution?: string; ready?: boolean; reason?: string | null};
export type Organic = {ready: boolean; execution: string; model?: string; reason?: string | null};
export type Config = {publisherId: string; mode: string; financialMode?: string; placementId: string; answerMode: string; organic?: Organic; engine?: Engine; sampleQuestions?: string[]; capabilities?: Array<{id: string; label: string; description: string}>};
export type Answer = {answer: string; answerMode: string; model?: string; advertiserMaterialIncluded: false; replayed?: boolean; trace?: Record<string, unknown>};
export type BudgetCampaign = {id: string; name: string; brandName: string; status: string; budgetCapBaseUnits: string; depositBaseUnits: string; maxBidBaseUnits: string; spendBaseUnits: string; reservedBaseUnits: string; remainingBaseUnits: string; authorizedBaseUnits: string; settledBaseUnits: string; refundBaseUnits: string; channelStatus: string; payment?: NativePayment};
export type WorkspaceState = FinancialMetadata & {mode: string; campaigns: BudgetCampaign[]; summary: Record<string, unknown>};
export type Turn = {input: OpportunityInput; submittedAt: number; answer?: Answer; answerReceivedAt?: number; answerError?: string; ad?: OpportunityResult; adReceivedAt?: number; adError?: string; adState: 'pending' | 'done' | 'disabled'; receipt?: ReceiptResult; receiptReceivedAt?: number; renderState?: 'pending' | 'accepted' | 'error' | 'failed'; renderError?: string; awardRelease?: 'pending' | 'released' | 'error'; domObservation?: RenderObservation; budgetAfterAward?: WorkspaceState; budgetAfterDelivery?: WorkspaceState; budgetError?: string; budgetLoading?: boolean; budgetFetchedAt?: number};
export type Candidate = {campaignId: string; name?: string; brandName?: string; declaredCapabilities?: string[]; advertiserContextHints?: string[]; contextHints?: string[]; eligible: boolean; reason?: string | null};
export type Evidence = {id?: string; text?: string; prompt?: string; hint?: string; source?: string; [key: string]: unknown};
export type Retrieval = {historyStatus?: string; method?: string; sourceHash?: string | null; profileHash?: string | null; exampleCount?: number; hintCount?: number; examples?: Evidence[]; hints?: Evidence[]; observedExamples?: Evidence[]; inferredHints?: Evidence[]};
export type Decision = {campaignId?: string; campaignVersionId?: string; decision: string; creativeVersionId?: string | null; relevanceLevel?: number | null; commercialIntentLevel?: number | null; reasonCodes?: string[]; engineProvenance?: {engine?: string; model?: string; execution?: string; outcome?: string; elapsedMs?: number; retrieval?: Retrieval; packetHash?: string; [key: string]: unknown}};
export type Bid = {campaignId: string; amountBaseUnits: string; bidPolicyVersion?: string};
export type LiveTrace = {payment?: NativePayment; engine?: string; execution?: string; context?: {coarseIntent?: string; taskConstraints?: string[]; softPreferences?: string[]; floorBaseUnits?: string; expiresAt?: number}; candidates?: Candidate[]; decisions?: Decision[]; bids?: Bid[]; rejections?: Array<{campaignId?: string; reason: string}>; timings?: Record<string, number>; [key: string]: unknown};
export function money(value?: string) {if (value === undefined) return 'Unavailable'; try {const n = BigInt(value); return `${n / 1000000n}.${(n % 1000000n).toString().padStart(6, '0').replace(/0+$/, '') || '0'}`;} catch {return value;}}
export function candidateFor(decision: Decision, candidates: Candidate[]) {return candidates.find(c => c.campaignId === decision.campaignId || decision.campaignVersionId?.startsWith(`${c.campaignId}-`));}
