"use client";
import {useState} from 'react';
import {Ld} from '@axp/design-system/ledger';
import {candidateFor, money, moneyUnit, financialModeOf, type LiveTrace, type Retrieval, type Turn} from './model';
import {isFinalizedNativeTransaction} from '../../../../../packages/publisher-sdk/financial.mjs';
import {NativePaymentEvidence} from './NativePaymentEvidence';

const readable = (value?: string) => value?.replaceAll('_', ' ') || 'Not reported';
function PublicEvidence({retrieval}: {retrieval: Retrieval}) {
  const observed = retrieval.examples ?? retrieval.observedExamples ?? [];
  const inferred = retrieval.hints ?? retrieval.inferredHints ?? [];
  return <div className="pub-stack"><div className="pub-between"><Ld.Tag tone={retrieval.historyStatus === 'ready' ? 'ch' : 'outline'}>ContextHint · {retrieval.historyStatus === 'ready' ? 'Available' : 'Unavailable'}</Ld.Tag><span className="ld-caption">{retrieval.exampleCount ?? observed.length} observed · {retrieval.hintCount ?? inferred.length} inferred</span></div>{observed.map((e, i) => <blockquote key={`observed-${i}`}><Ld.Tag tone="ch">Observed</Ld.Tag><p>{e.text || e.prompt || 'See raw evidence record.'}</p></blockquote>)}{inferred.map((e, i) => <blockquote key={`inferred-${i}`}><Ld.Tag tone="ch">Inferred</Ld.Tag><p>{e.text || e.hint || 'See raw evidence record.'}</p></blockquote>)}<p className="ld-caption">Historical associations support judgment. They do not verify capabilities or predict conversion.</p><details className="pub-details"><summary>Retrieval records</summary><pre>{JSON.stringify(retrieval, null, 2)}</pre></details></div>;
}

export function PeekInside({turn, financialMode, onRefreshBudget, onRetryAd, onRetryRender, pending}: {
  turn: Turn; financialMode?: string; onRefreshBudget?: () => void; onRetryAd?: () => void; onRetryRender?: () => void; pending?: boolean;
}) {
  const [active, setActive] = useState(2);
  const trace = turn.ad?.trace as LiveTrace | undefined;
  const candidates = trace?.candidates ?? [], decisions = trace?.decisions ?? [], bids = trace?.bids ?? [];
  const award = turn.ad?.status === 'awarded' ? turn.ad.award : undefined;
  const budget = turn.budgetAfterDelivery ?? turn.budgetAfterAward;
  const mode = financialModeOf(turn.receipt, turn.ad, budget, {financialMode});
  const unit = moneyUnit(mode);
  const winnerBudget = award ? budget?.campaigns.find(c => c.id === award.campaignId) : undefined;
  const payment = (turn.budgetAfterDelivery ? winnerBudget?.payment : undefined) ?? turn.receipt?.payment ?? winnerBudget?.payment ?? trace?.payment;
  const finalizedClose = payment?.network === 'solana-devnet' && payment.transactions?.some(tx => tx.operation === 'close' && isFinalizedNativeTransaction(tx));
  const label = (id?: string) => {const c = candidates.find(c => c.campaignId === id); return c?.brandName || c?.name || budget?.campaigns.find(c => c.id === id)?.brandName || id || 'Campaign';};
  const eligible = candidates.filter(c => c.eligible).length;
  const complete = !!turn.ad, skipped = turn.adState === 'disabled';
  const sponsoredState = turn.domObservation?.domInserted ? 'Inserted' : turn.answerError ? 'Omitted' : skipped ? 'Disabled' : turn.adError ? 'Failed' : turn.ad?.status === 'no_fill' ? 'No fill' : 'Pending';
  const status = complete ? 'done' as const : skipped ? 'skipped' as const : 'upcoming' as const;
  // Bar widths are a visual projection only. Exact financial values remain server strings.
  const maximum = Math.max(1, Number(trace?.context?.floorBaseUnits || 0), ...bids.map(b => Number(b.amountBaseUnits)));
  const stages = [
    {id: 'context', label: 'Context', value: complete ? `${eligible} / ${candidates.length} eligible` : skipped ? 'Disabled' : 'Unavailable', status},
    {id: 'buyers', label: 'Buyers', value: complete ? `${decisions.length} judgments` : 'No records', status},
    {id: 'auction', label: 'Auction', value: award ? `${money(award.priceBaseUnits)} ${unit}` : complete ? 'No fill' : 'No award', status},
    {id: 'delivery', label: 'Delivery', value: turn.receipt ? 'Accepted' : turn.renderError ? 'Unconfirmed' : award ? 'Pending' : 'No card', status: turn.receipt ? 'done' as const : !award && (complete || skipped) ? 'skipped' as const : 'upcoming' as const},
    {id: 'payment', label: 'Payment', value: mode === 'synthetic' ? 'Test credits' : finalizedClose ? 'Settled' : turn.receipt?.authorization?.status === 'authorized' ? 'Authorized' : payment?.phase || 'No charge', status: finalizedClose || turn.receipt?.authorization?.status === 'authorized' ? 'done' as const : 'upcoming' as const},
  ];
  return <div className="pub-inspector" id="publisher-peek">
    <section className="pub-flow-map" aria-label="Independent answer and advertising requests">
      <div className="pub-flow-source"><span className="ld-label">Question</span><p>{turn.input.question}</p></div><span className="pub-flow-branch" aria-hidden />
      <div className="pub-flow-lanes"><div className="pub-flow-lane"><div><b>DeepSeek</b><span>Organic answer only</span></div><span aria-hidden>→</span><div><b>Answer</b><span>{turn.answer ? 'Generated' : turn.answerError ? 'Failed' : 'Pending'}</span></div></div><div className="pub-flow-lane pub-flow-lane-ad"><div><b>AXP exchange</b><span>{skipped ? 'Not requested' : trace?.engine || 'Jev buying agents'}</span></div><span aria-hidden>→</span><div><b>Sponsored</b><span>{sponsoredState}</span></div></div></div>
    </section>
    <div className="pub-between pub-inspector-label"><span className="ld-label">Sponsored lane</span><Ld.Tag tone="outline">{mode === 'devnet' ? 'Solana Devnet · test USDC' : mode === 'synthetic' ? 'Synthetic test credits' : mode || 'Mode unavailable'}</Ld.Tag></div>
    <div className="ld-pipe" role="tablist" aria-label="Sponsored flow" style={{gridTemplateColumns: 'repeat(5, minmax(0, 1fr))'}} onKeyDown={event => {
      if (!['ArrowRight', 'ArrowLeft', 'Home', 'End'].includes(event.key)) return;
      event.preventDefault();
      const next = event.key === 'Home' ? 0 : event.key === 'End' ? 4 : (active + (event.key === 'ArrowRight' ? 1 : 4)) % 5;
      setActive(next); event.currentTarget.querySelectorAll<HTMLButtonElement>('[role="tab"]')[next]?.focus();
    }}>{stages.map((stage, i) => <button key={stage.id} type="button" role="tab" id={`pub-tab-${stage.id}`} aria-controls="pub-stage-panel" aria-current={active === i ? 'step' : undefined} aria-selected={active === i} tabIndex={active === i ? 0 : -1} className="ld-pipe-step" data-status={stage.status} onClick={() => setActive(i)}><span className="ld-pipe-top"><span className="ld-pipe-ix">{stage.status === 'done' && active !== i ? '✓' : i + 1}</span>{stage.label}</span><span className="ld-pipe-v">{stage.value}</span></button>)}</div>
    <section id="pub-stage-panel" className="pub-stage-content" role="tabpanel" aria-labelledby={`pub-tab-${stages[active].id}`} tabIndex={0}>
      {active === 0 ? <><div className="pub-stage-heading"><h3>Who can participate?</h3><span>{eligible} of {candidates.length} campaigns</span></div>{trace?.context ? <><div className="pub-chip-row">{trace.context.taskConstraints?.map(c => <Ld.Tag key={c}>{readable(c)}</Ld.Tag>)}</div><div className="pub-candidate-list">{candidates.map(c => <div key={c.campaignId}><b>{c.brandName || c.name || c.campaignId}</b><span>{c.eligible ? 'Declared capabilities match' : readable(c.reason ?? undefined)}</span><Ld.Tag tone={c.eligible ? 'success' : 'outline'}>{c.eligible ? 'Eligible' : 'Excluded'}</Ld.Tag></div>)}</div><details className="pub-details"><summary>Context and policy records</summary><pre>{JSON.stringify({context: trace.context, candidates}, null, 2)}</pre></details></> : <p>{skipped ? 'Sponsored suggestions were disabled for this turn.' : turn.adError ? `Exchange request failed: ${turn.adError}` : 'No context records returned.'}</p>}</> : null}
      {active === 1 ? <><div className="pub-stage-heading"><h3>How did each buyer decide?</h3><span>{trace?.engine || 'Jev'}</span></div><div className="pub-buyers">{decisions.map((d, i) => {const c = candidateFor(d, candidates); return <div className="pub-buyer" key={d.campaignVersionId ?? i}><div className="pub-buyer-result"><b>{c?.brandName || c?.name || d.campaignVersionId || 'Buyer'}</b><div><span>Relevance</span><b>{d.relevanceLevel == null ? 'Unavailable' : `${d.relevanceLevel} / 3`}</b></div><div><span>Intent</span><b>{d.commercialIntentLevel == null ? 'Unavailable' : `${d.commercialIntentLevel} / 3`}</b></div><Ld.Tag tone={d.decision === 'bid' ? 'brand' : 'outline'}>{readable(d.decision)}</Ld.Tag></div><details className="pub-details"><summary>Buyer context and evidence</summary><div className="pub-stack"><div><Ld.Tag>Advertiser declared</Ld.Tag>{(c?.advertiserContextHints ?? c?.contextHints ?? []).map((hint, j) => <p key={j}>{hint}</p>)}<p className="ld-caption">Capabilities: {c?.declaredCapabilities?.map(readable).join(', ') || 'Not reported'}</p></div>{d.engineProvenance?.retrieval ? <PublicEvidence retrieval={d.engineProvenance.retrieval} /> : null}<div className="pub-facts"><span>Model</span><b className="ld-mono">{d.engineProvenance?.model || trace?.engine}</b><span>Execution</span><b>{d.engineProvenance?.execution || 'Not reported'}</b><span>Recorded buyer time</span><b>{d.engineProvenance?.elapsedMs == null ? 'Unavailable' : `${Math.round(d.engineProvenance.elapsedMs)} ms`}</b><span>Reasons</span><b>{d.reasonCodes?.map(readable).join(', ') || 'Not reported'}</b></div><details className="pub-details"><summary>Decision record</summary><pre>{JSON.stringify(d, null, 2)}</pre></details></div></details></div>;})}</div>{!decisions.length ? <p>No buyer judgments returned.</p> : <p className="ld-caption">Jev selects fit and creative. Code controls bids and money. Scores are rubric levels, not conversion probabilities.</p>}</> : null}
      {active === 2 ? <><div className="pub-stage-heading"><h3>{award ? `${label(award.campaignId)} won the placement` : 'No sponsored placement awarded'}</h3><span>First-price auction</span></div>{bids.length ? <div className="pub-auction-chart" aria-label={`Admitted bids in ${unit}`}><div className="pub-chart-label"><span>Admitted bid</span><span>{unit}</span></div>{[...bids].sort((a, b) => Number(b.amountBaseUnits) - Number(a.amountBaseUnits)).map(b => <div className="pub-bid-row" key={b.campaignId} data-winner={b.campaignId === award?.campaignId || undefined}><div className="pub-between"><b>{label(b.campaignId)}</b><div><strong>{money(b.amountBaseUnits)}</strong>{b.campaignId === award?.campaignId ? <Ld.Tag tone="brand">Winner</Ld.Tag> : <span className="ld-caption">No charge</span>}</div></div><div className="pub-bid-track" title={`${label(b.campaignId)}: ${money(b.amountBaseUnits)} ${unit}`}><div style={{width: `${Number(b.amountBaseUnits) / maximum * 100}%`}} /><span className="pub-floor-mark" style={{left: `${Number(trace?.context?.floorBaseUnits || 0) / maximum * 100}%`}} /></div></div>)}<div className="pub-chart-axis"><span>0</span><span>Floor {money(trace?.context?.floorBaseUnits)} {unit}</span><span>{money(String(maximum))}</span></div></div> : <p>No admitted bid. No award or reservation.</p>}<p className="ld-caption">{award ? 'The winning bid reserves budget. Only accepted delivery creates a charge.' : 'The answer is independent of the auction outcome.'}</p>{trace?.rejections?.length ? <details className="pub-details"><summary>Why other bids were excluded</summary>{trace.rejections.map((r, i) => <p key={i}><b>{label(r.campaignId)}</b>: {readable(r.reason)}</p>)}</details> : null}{turn.adError && onRetryAd ? <Ld.Button variant="secondary" onClick={onRetryAd} disabled={pending}>Retry ad request</Ld.Button> : null}</> : null}
      {active === 3 ? <><div className="pub-stage-heading"><h3>{turn.receipt ? 'One delivery. One charge.' : 'Delivery checks'}</h3>{turn.receipt ? <Ld.Tag tone="success">Accepted</Ld.Tag> : null}</div><div className="pub-delivery-checks">{[['Exact approved copy in the DOM', !!turn.domObservation?.domInserted], ['Sponsored disclosure present', !!turn.domObservation?.sponsoredLabelPresent], ['Signed receipt accepted', !!turn.receipt]].map(([name, done]) => <div key={String(name)}><span className={done ? 'pub-check-done' : ''} aria-hidden>{done ? '✓' : '·'}</span><b>{name}</b><span>{done ? 'Confirmed' : 'Not confirmed'}</span></div>)}</div>{turn.receipt ? <div className="pub-accepted-amount"><span className="ld-label">Accepted charge</span><b>{money(turn.receipt.charge.amountBaseUnits)} <small>{unit}</small></b><span className="ld-caption">{turn.receipt.replayed ? 'Existing receipt returned. No additional charge.' : 'Created from the app’s signed observation.'}</span></div> : <p>{turn.answerError ? `Card omitted. ${turn.awardRelease === 'released' ? 'Reservation released.' : 'Release unconfirmed; server expiry remains active.'}` : turn.renderError ? `Delivery unconfirmed: ${turn.renderError}` : !award ? 'No awarded card was inserted.' : 'Waiting for the placement observation.'}</p>}<p className="ld-caption">The signature authenticates insertion and disclosure. It does not prove attention or conversion.</p>{award && turn.answer && turn.renderState !== 'pending' && onRetryRender ? <Ld.Button variant="secondary" disabled={pending} onClick={onRetryRender}>{turn.receipt ? 'Replay same receipt' : 'Retry acknowledgement'}</Ld.Button> : null}<details className="pub-details"><summary>Creative binding and signed receipt</summary><pre>{JSON.stringify({award, observation: turn.domObservation, receipt: turn.receipt, authorization: turn.receipt?.authorization}, null, 2)}</pre></details></> : null}
      {active === 4 ? <><div className="pub-stage-heading"><h3>Where is the money?</h3><span>{winnerBudget?.brandName || 'No winning campaign'}</span></div>{winnerBudget ? <><div className="pub-money-grid">{[['Deposit', winnerBudget.depositBaseUnits], ['Accepted', winnerBudget.spendBaseUnits], ['Authorized', winnerBudget.authorizedBaseUnits], ['Settled', winnerBudget.settledBaseUnits], ['Refunded', winnerBudget.refundBaseUnits], ['Remaining cap', winnerBudget.remainingBaseUnits]].map(([name, amount]) => <div key={name}><span>{name}</span><b>{mode === 'devnet' && (name === 'Settled' || name === 'Refunded') && !finalizedClose ? 'Not finalized' : money(amount)}</b><span>{unit}</span></div>)}</div><p className="ld-caption">Reserved: {money(winnerBudget.reservedBaseUnits)} {unit}. {mode === 'devnet' ? 'Authorization is off-chain. Payout and refund require finalized close evidence.' : 'Synthetic credits have no blockchain payout.'}</p></> : <p>{budget ? 'No winning campaign to charge.' : 'Budget records unavailable.'}</p>}<NativePaymentEvidence payment={payment} />{turn.receipt?.authorization?.reason ? <p role="status">{turn.receipt.authorization.reason}</p> : null}{onRefreshBudget && complete ? <Ld.Button variant="ghost" onClick={onRefreshBudget} disabled={turn.budgetLoading}>{turn.budgetLoading ? 'Refreshing…' : 'Refresh payment records'}</Ld.Button> : null}{turn.budgetError ? <p role="status">Refresh failed: {turn.budgetError}</p> : null}{turn.budgetFetchedAt ? <p className="ld-caption">Server records fetched {new Date(turn.budgetFetchedAt).toLocaleTimeString()}.</p> : null}</> : null}
    </section>
    <details className="pub-details pub-raw-records"><summary>Request and raw records</summary><p>{turn.input.question}</p><pre>{JSON.stringify({request: turn.input, organic: {mode: turn.answer?.answerMode, model: turn.answer?.model, advertiserMaterialIncluded: turn.answer?.advertiserMaterialIncluded, trace: turn.answer?.trace, error: turn.answerError}, exchange: trace ?? {status: turn.adState, error: turn.adError}}, null, 2)}</pre></details>
  </div>;
}
