export type FinancialMode = 'sandbox' | 'synthetic';
export type Presentation = 'interactive-reference' | 'recorded_evidence_replay';
export type Capability = 'crypto_storage' | 'hardware_wallet' | 'offline_key_storage' | 'ethereum' | 'solana' | 'mobile_software_wallet' | 'physical_wallet' | 'rfid_blocking';
export type RetrievalMethod = 'vector' | 'lexical_fallback' | 'unavailable';
export interface CampaignDraftInput {campaignId:string;businessName?:string;creative?:string;contextHints?:string;approved?:boolean;status?:'active'|'paused';maxBidBaseUnits?:string;budgetCapBaseUnits?:string;declaredConstraints?:Capability[]}
export interface CampaignDraft {campaign:Campaign;businessName:string;contextHints:string;approved:boolean;fictional:true;version:number}
export interface Campaign {campaignId:string;campaignVersionId:string;advertiserId:string;status:'active'|'paused';allowedIntents:string[];destination:string;declaredConstraints:Capability[];creatives:Creative[];maxBidBaseUnits:string;budgetCapBaseUnits:string;channelId:string;policyVersion:string;softFitTags:string[]}
export interface Creative {creativeVersionId:string;approvedText:string;destinationURL:string;fictional:true;softFitTags:string[];evidenceFieldIds:string[]}
export type TurnInput = {scenarioId:'cached'|'offline'|'repeat'|'mobile';financialMode?:'sandbox'} | {financialMode:'synthetic';turnId:string;question:string;mandatoryCapabilities:Capability[]};
export interface Retrieval {method:RetrievalMethod;fallback:boolean;sourceHash:string;examples:Array<{id:string;text:string;promptId?:number;creativeId?:number;hintIds?:string[]}>;hints:Array<{id:string;text:string;tier:string;qualityFlags:string[]}>;profile:Record<string,unknown>|null}
export interface OrganicAnswer {schemaVersion:'axp.v3-organic.v1';runId:string;turnId:string;question:string;requestId:string;inputHash:string;suppliedPrompt:string;model:'gpt-6.1-sol';effort:'low';status:'waiting'|'completed';advertiserMaterialReceived:false;answer?:string;provenance?:Record<string,unknown>}
export interface DecisionRecord {slotId:string;callId:string;arm:'text_only'|'history';category:'paired'|'repeat'|'laboratory'|'correction';campaignId:string;campaignVersionId:string;opportunityId:string;question:string;admitted:boolean;status:'pending'|'admitted'|'completed'|'failed'|'uncertain'|'unavailable';request:Record<string,unknown>;packet:Record<string,unknown>|null;packetHash:string;bindings:Record<string,unknown>;retrieval:Retrieval|null;decision:Record<string,unknown>|null;elapsedMs:number|null;failure:Record<string,unknown>|null}
export interface Turn {turnId:string;question:string;financialMode:FinancialMode;status:'waiting_organic'|'ready'|'completed';organic:OrganicAnswer;scenario:{id:string;question:string;questionIndex:number;mandatoryCapabilities:Capability[];paired:boolean}|null;opportunityId?:string;records?:DecisionRecord[];outcome?:{status:'awarded'|'no_fill';award?:Award;bids:Array<Record<string,unknown>>;rejections?:Array<Record<string,unknown>>};eligibility?:Record<string,unknown>}
export interface Award {id:string;opportunityId:string;campaignId:string;campaignVersionId:string;channelId:string;priceBaseUnits:string;creative:Creative;creativeHash:string;status:string}
export interface ChannelEvidence {channelId:string;runId:string;mode:'sandbox';protocolChannelId:string|null;openStatus:string;closeStatus:string|null;depositBaseUnits:string;acceptedBaseUnits:string;authorizedBaseUnits:string;settledBaseUnits:string;refundBaseUnits:string;network:string;genesisHash:string;program:string;mint:string;payer:string;payee:string;vouchers:Array<{chargeId:string;sequence:string;status:string;incrementBaseUnits:string;cumulativeAmountBaseUnits:string;payloadHash:string|null;voucherRecordHash:string|null}>;settlementLink:string|null}
export interface V3State {schemaVersion:'axp.v3-state.v1';runId:string;presentation:Presentation;financialMode:'sandbox';replay?:boolean;running:boolean;modelEnabled:boolean;model:Record<string,unknown>;organicAllowance:{limit:number;admitted:number;remaining:number};drafts:CampaignDraft[];freeze:Record<string,unknown>|null;turns:Turn[];laboratory:{financialMode:'synthetic';turns:Turn[];exchange:Record<string,unknown>};exchange:{charges:Array<Record<string,unknown>>;awards:Award[];[key:string]:unknown};payments:ChannelEvidence[];limitations:string[]}
export interface Bootstrap {schemaVersion:'axp.v3-bootstrap.v1';csrf:string|null;replay:boolean;readOnly:boolean;runId:string;scenarios:Array<{id:string;question:string;questionIndex:number;mandatoryCapabilities:Capability[];paired:boolean}>;policy:Record<string,unknown>;manifest:Record<string,unknown>}
export interface V3Client {bootstrap():Promise<Bootstrap>;state():Promise<V3State>;events():Promise<Array<Record<string,unknown>>>;catalogue():Promise<Record<string,unknown>>;retrieval(question:string,campaignId:string):Promise<Retrieval|null>;saveCampaign(body:CampaignDraftInput):Promise<CampaignDraft>;preview(body:TurnInput):Promise<Record<string,unknown>>;requestTurn(body:TurnInput):Promise<Turn>;runTurn(body:TurnInput):Promise<V3State>;render(id:string,body:{financialMode?:FinancialMode;domInserted:boolean;sponsoredLabelPresent:boolean;creativeHash:string}):Promise<Record<string,unknown>>;fail(id:string,body?:{financialMode?:FinancialMode}):Promise<Record<string,unknown>>}
export function createClient(options?:{baseURL?:string;replay?:boolean;fetcher?:typeof fetch}):V3Client;
