// One trusted local Devnet payment worker. Browser actions select approved campaigns,
// never keys, recipients, network, voucher bytes or charge amounts.
import {mkdirSync,openSync,closeSync,readFileSync,writeFileSync,unlinkSync,existsSync,statfsSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {randomBytes} from 'node:crypto';
import {SQLitePaymentStore} from '../payments/store.mjs';
import {NetworkPaymentAdapter,hashNetworkRecord,hashNetworkTerms} from '../payments/network-adapter.mjs';
import {createNativeTransport} from '../payments/sdk-transport.mjs';
import {ledgerCharge,ledgerObligations} from '../v3/devnet-live.mjs';
import {NATIVE_LIMITS,network,check,walletIdentities,inspectProductDevnet} from './native.mjs';
const money=x=>{check(typeof x==='string'&&/^(0|[1-9][0-9]*)$/.test(x),'payment_amount_invalid');return BigInt(x);};
const uncertain=s=>s&&(!['prepared','finalized','failed'].includes(s.open.status)||(s.close&&!['prepared','finalized','failed'].includes(s.close.status))||s.intents.some(i=>i.status!=='authorized'));
const safeReason=e=>/^[a-z_0-9]+$/.test(e?.reasonCode??e?.code??'')?(e.reasonCode??e.code):'payment_operation_blocked';
export function createProductPayments({exchange,stateDir,walletPath,signingEnabled=false,identities,preflight=inspectProductDevnet,transportFactory=createNativeTransport,now=Date.now,lock=true}={}){
 check(exchange.mode==='devnet','payment_mode_conflict');mkdirSync(stateDir,{recursive:true,mode:0o700});
 const ids=identities??walletIdentities(walletPath);
 const directory=resolve(stateDir),lockPath=join(directory,'payment-worker.lock');let ownsLock=false;
 if(lock){if(existsSync(lockPath)){const owner=JSON.parse(readFileSync(lockPath,'utf8'));let live=true;try{process.kill(owner.pid,0);}catch(e){if(e.code==='ESRCH')live=false;}check(!live,'payment_worker_already_running');unlinkSync(lockPath);}const fd=openSync(lockPath,'wx',0o600);writeFileSync(fd,JSON.stringify({pid:process.pid}));closeSync(fd);ownsLock=true;}
 const store=new SQLitePaymentStore(join(directory,'payments.sqlite'));
 store.db.exec('CREATE TABLE IF NOT EXISTS product_payment_terms(id TEXT PRIMARY KEY,data TEXT NOT NULL)');
 const load=id=>{const row=store.db.prepare('SELECT data FROM product_payment_terms WHERE id=?').get(id);return row?JSON.parse(row.data):null;};
 const termsList=()=>store.db.prepare('SELECT data FROM product_payment_terms ORDER BY id').all().map(r=>JSON.parse(r.data));
 const save=t=>store.db.prepare('INSERT INTO product_payment_terms VALUES(?,?)').run(t.channelId,JSON.stringify(t));
 const transports=new Map(),adapters=new Map();let tail=Promise.resolve(),disposed=false;
 const queued=fn=>{const p=tail.catch(()=>{}).then(async()=>{check(!disposed,'payment_worker_disposed');try{return await fn();}catch(e){return {status:'blocked',reason:safeReason(e),reasonCode:safeReason(e)};}});tail=p;return p;};
 const totals=()=>{const terms=termsList();return {channels:terms.length,deposits:terms.reduce((s,t)=>s+money(t.depositBaseUnits),0n),fees:terms.reduce((n,t)=>{const s=store.get(t.channelId);return n+['open','close'].reduce((v,kind)=>{const estimate=money(s?.[kind]?.signed?.estimatedFeeAndRentLamports??s?.[kind]?.plan?.estimatedFeeAndRentLamports??'0');return v+(estimate>5000000n?estimate:5000000n);},0n);},0n)};};
 function verifyLedger(){let accepted=0n,reserved=0n;for(const t of termsList()){const o=ledgerObligations(exchange,t.channelId);check(o.charges.length<=NATIVE_LIMITS.maxCharges,'delivery_cap_exceeded');check(money(o.acceptedBaseUnits)+money(o.reservedBaseUnits)<=money(t.chargeCapBaseUnits),'campaign_payment_cap');accepted+=money(o.acceptedBaseUnits);reserved+=money(o.reservedBaseUnits);for(const c of o.charges){check(c.runId===t.runId&&c.channelId===t.channelId&&c.advertiserId===t.advertiserId&&c.campaignVersionId===t.campaignVersionId,'charge_terms_mismatch');check(c.mode==='devnet'&&exchange.require('awards',c.awardId).payee===ids.payee&&c.acceptedReceiptHash&&c.amountBaseUnits,'charge_binding');}}check(accepted+reserved<=money(NATIVE_LIMITS.aggregateChargeBaseUnits),'aggregate_charge_cap');return {accepted,reserved};}
 async function beforeSign(id,operation){check(signingEnabled===true,'devnet_signing_disabled');const t=load(id);check(t&&t.payer===ids.payer&&t.payee===ids.payee,'payment_identity_changed');const aggregate=totals();check(aggregate.channels<=NATIVE_LIMITS.maxChannels&&aggregate.deposits<=money(NATIVE_LIMITS.aggregateDepositBaseUnits),'aggregate_deposit_cap');check(aggregate.fees<=money(NATIVE_LIMITS.aggregateFeeRentLamports),'aggregate_fee_cap');verifyLedger();for(const s of store.list())if(s.channelId!==id)check(!uncertain(s),'payment_reconciliation_required');if(operation!=='voucher'){const report=await preflight({...ids,depositBaseUnits:t.depositBaseUnits,expected:t,simulate:false});check(report.compatible,'native_preflight_failed');check(money(report.balances.payerLamports)>=aggregate.fees,'insufficient_devnet_sol');if(operation==='open')check(money(report.balances.payerBaseUnits)>=money(t.depositBaseUnits),'insufficient_test_usdc');}}
 async function adapter(id){const t=load(id);check(t,'payment_terms_missing');if(adapters.has(id))return adapters.get(id);const transport=await transportFactory({terms:t,statePath:join(directory,'native.sqlite'),walletPath});transports.set(id,transport);const a=new NetworkPaymentAdapter({store,protocolTransport:transport,getLedgerCharge:c=>ledgerCharge(exchange,c),getLedgerObligations:c=>ledgerObligations(exchange,c),approvalTermsHash:hashNetworkTerms(t),limits:NATIVE_LIMITS,beforeSigning:({operation})=>beforeSign(id,operation),now:()=>Math.floor(now()/1000)});adapters.set(id,a);return a;}
 function projection(id){const s=store.get(id);if(!s)return null;return {channelId:id,runId:s.terms.runId,mode:'devnet',phase:uncertain(s)&&s.phase==='open'?'draining':s.phase,openStatus:s.open.status,closeStatus:s.close?.status??null,depositBaseUnits:s.open.status==='finalized'?s.terms.depositBaseUnits:'0',authorizedBaseUnits:s.authorizedBaseUnits,acceptedBaseUnits:s.acceptedBaseUnits,settledBaseUnits:s.close?.status==='finalized'?s.close.receipt.settledBaseUnits:'0',refundBaseUnits:s.close?.status==='finalized'?s.close.receipt.refundBaseUnits:'0',protocolChannelId:s.protocolChannelId??null,termsHash:s.termsHash,reconciliationRequired:Boolean(uncertain(s))};}
 function evidence(id){const t=load(id),s=store.get(id),p=projection(id);if(!t)return null;const obligations=ledgerObligations(exchange,id),transactions=[];
 for(const operation of ['open','close']){const op=s?.[operation];if(!op)continue;const signature=op.signed?.txSignature??null,proof=op.status==='finalized'?op.receipt?.evidence:null;transactions.push({operation,status:op.status,signature,explorerURL:signature?`https://explorer.solana.com/tx/${signature}?cluster=devnet`:null,finality:op.receipt?.finality??null,...(proof?{slot:proof.slot,blockTime:proof.blockTime,networkFeeLamports:proof.networkFeeLamports,newRentLamports:proof.newRentLamports,reclaimedRentLamports:proof.reclaimedRentLamports,tokenDeltas:proof.tokenDeltas}:{}),reason:op.reasonCode??null});}
 const vouchers=(s?.intents??[]).map(i=>({chargeId:i.charge.id,status:i.status,sequence:i.sequence,incrementBaseUnits:i.charge.amountBaseUnits,cumulativeAmountBaseUnits:i.cumulativeAmountBaseUnits,payloadHash:i.payloadHash??null}));
 return {mode:'devnet',network:'solana-devnet',channelId:id,protocolChannelId:p?.protocolChannelId??null,address:p?.protocolChannelId??null,payer:t.payer,payee:t.payee,mint:t.mint,phase:p?.phase??'pending_open',openStatus:p?.openStatus??'not_prepared',closeStatus:p?.closeStatus??null,depositBaseUnits:t.depositBaseUnits,confirmedDepositBaseUnits:p?.depositBaseUnits??'0',acceptedBaseUnits:obligations.acceptedBaseUnits,authorizedBaseUnits:p?.authorizedBaseUnits??'0',settledBaseUnits:p?.settledBaseUnits??'0',refundBaseUnits:p?.refundBaseUnits??'0',reconciliationRequired:p?.reconciliationRequired??false,canReconcile:Boolean(uncertain(s)),canRetryOpen:Boolean(!s||(s.open.status==='prepared'&&!s.open.signed&&!s.close)),canSettle:Boolean(s?.open.status==='finalized'&&!uncertain(s)&&!s.close&&obligations.reservedBaseUnits==='0'&&s.authorizedBaseUnits===obligations.acceptedBaseUnits),reason:s?.close?.reasonCode??s?.open.reasonCode??null,expiresAt:t.voucherExpiresAt,transactions,vouchers};
 }
 function sync(id){if(!exchange.get('channels',id))return;exchange.syncNetworkChannel(id);const s=store.get(id);if(!s)return;exchange.tx(()=>{for(const i of s.intents)if(i.status==='authorized'){const c=exchange.require('charges',i.charge.id),status=s.close?.status==='finalized'?'settled':'authorized';if(c.status!==status){c.status=status;exchange.put('charges',c.id,c);exchange.event(status==='settled'?'devnet_charge_settled':'devnet_voucher_authorized',{channelId:id,chargeId:c.id,cumulativeAmountBaseUnits:i.cumulativeAmountBaseUnits});}}});}
 const freeze=campaign=>queued(async()=>{const id=campaign.channelId,old=load(id);if(old){check(old.campaignVersionId===campaign.campaignVersionId&&old.depositBaseUnits===exchange.require('channels',id).depositBaseUnits,'payment_terms_changed');return {status:'frozen',replayed:true};}check(signingEnabled,'devnet_signing_disabled');const deposit=exchange.require('channels',id).depositBaseUnits;
 check(money(deposit)>0n&&money(deposit)<=money(NATIVE_LIMITS.maxDepositBaseUnits)&&money(campaign.budgetCapBaseUnits)<=money(NATIVE_LIMITS.maxBudgetBaseUnits)&&money(campaign.budgetCapBaseUnits)<=money(deposit)&&money(campaign.maxBidBaseUnits)<=money(NATIVE_LIMITS.maxBidBaseUnits),'native_campaign_limit');const a=totals();check(a.channels<NATIVE_LIMITS.maxChannels&&a.deposits+money(deposit)<=money(NATIVE_LIMITS.aggregateDepositBaseUnits),'aggregate_deposit_cap');check(a.fees+10000000n<=money(NATIVE_LIMITS.aggregateFeeRentLamports),'aggregate_fee_cap');check(statfsSync(directory).bavail*statfsSync(directory).bsize>=50*1024**3,'50gib_disk_floor');
 const report=await preflight({...ids,depositBaseUnits:deposit,simulate:true});check(report.compatible&&report.simulation?.err===null,'native_feasibility_required');const time=Math.floor(now()/1000),{treasuryOwner,...env}=network;
 const t={...env,runId:exchange.runId,channelId:id,advertiserId:campaign.advertiserId,campaignVersionId:campaign.campaignVersionId,...ids,depositBaseUnits:deposit,maxBidBaseUnits:campaign.maxBidBaseUnits,chargeCapBaseUnits:campaign.budgetCapBaseUnits,maxCharges:NATIVE_LIMITS.maxCharges,zeroChargeClose:true,openSalt:(BigInt(`0x${randomBytes(8).toString('hex')}`)||1n).toString(),voucherExpiresAt:time+86400,applicationDeadlineAt:time+85500,settlementMarginSeconds:60,compatibilityHash:hashNetworkRecord(report),programAccountHash:report.programAccountHash,programDataHash:report.programDataHash,treasuryOwner};save(t);return {status:'frozen',replayed:false};});
 const open=id=>queued(async()=>{const a=await adapter(id),t=load(id);if(!store.get(id))await a.prepareOpen(t);const s=store.get(id);const r=await a.confirmOpen({channelId:id,planId:s.open.id});sync(id);return r;});
 const drain=id=>queued(async()=>{const a=await adapter(id),s=store.get(id);if(s.phase==='open')await a.beginDrain({channelId:id});sync(id);return {status:'draining'};});
 const authorize=id=>queued(async()=>{const a=await adapter(id);verifyLedger();const results=[];for(const c of ledgerObligations(exchange,id).charges){const r=await a.authorizeCumulative({channelId:id,chargeId:c.id});results.push(r);sync(id);if(r.status!=='authorized')break;}return {status:results.every(r=>r.status==='authorized')?'authorized':'unknown',authorizations:results};});
 const close=id=>queued(async()=>{const a=await adapter(id);verifyLedger();const s=store.get(id);if(s.close){const r=await a.confirmClose({channelId:id,planId:s.close.id});sync(id);return r;}if(s.phase==='open')await a.beginDrain({channelId:id});const plan=await a.prepareClose({channelId:id});if(plan.status!=='prepared'){sync(id);return plan;}const r=await a.confirmClose({channelId:id,planId:plan.planId});sync(id);return r;});
 const reconcile=id=>queued(async()=>{const a=await adapter(id);let r=await a.reconcile({channelId:id});for(const i of store.get(id).intents.filter(i=>i.status!=='authorized'))r=await a.reconcile({channelId:id,chargeId:i.charge.id});sync(id);return r;});
 return {identities:ids,freeze,open,drain,authorize,close,reconcile,projection,evidence,sync,store,status:()=>({mode:'devnet',network:'solana-devnet',ready:signingEnabled,reason:signingEnabled?null:'devnet_signing_disabled',signingEnabled,...ids,mint:network.mint,limits:NATIVE_LIMITS}),dispose:()=>{disposed=true;for(const t of transports.values())t.close?.();store.close();if(ownsLock){unlinkSync(lockPath);ownsLock=false;}}};
}
