'use client';

import { useEffect, useMemo, useState } from 'react';
import { ActionText } from '@axp/design-system/prospectus';
import { count, normalize, num, object, short, str, usdc, type PublicRecord, type Channel } from './record';
import s from '@/app/network/network.module.css';

const ext = { target: '_blank', rel: 'noopener noreferrer' } as const;
function Proof({ href, children }: { href: string; children: string }) { return href ? <a href={href} {...ext}>{children} ↗</a> : null; }
function Stat({ value, label, detail }: {value: unknown; label: string; detail?: string}) { return <div className={s.stat}><strong>{value == null ? '·' : count(value)}</strong><span>{label}</span>{detail && <small>{detail}</small>}</div>; }
function Amount({ label, amount, state }: { label: string; amount: unknown; state: string }) { return <div className={s.amount} data-money={state}><span>{label}</span><strong>{usdc(amount)} <small>test USDC</small></strong></div>; }
function ChannelProof({ channel }: { channel: Channel }) {
  return <><div className={s.inspectHeading}><span>Solana Devnet channel</span><span className={s.phase}>{channel.paymentPhase.replaceAll('_', ' ')}</span></div>
    <h3>{channel.name || short(channel.id)}</h3>
    <div className={s.channelMeter}><i style={{width: `${channel.depositBaseUnits ? Math.min(100, channel.acceptedBaseUnits / channel.depositBaseUnits * 100) : 0}%`}} /></div>
    <div className={s.amounts}><Amount label="Deposited" amount={channel.depositBaseUnits} state="deposit" /><Amount label="Accepted deliveries" amount={channel.acceptedBaseUnits} state="accepted" /><Amount label="Authorized off-chain" amount={channel.authorizedBaseUnits} state="authorized" /><Amount label="Settled to publisher" amount={channel.settledBaseUnits} state="settled" /><Amount label="Refunded" amount={channel.refundBaseUnits} state="refunded" /></div>
    <div className={s.proofLinks}><Proof href={channel.openUrl}>Opening transaction</Proof><Proof href={channel.closeUrl}>Closing transaction</Proof><Proof href={channel.channelUrl}>Channel account</Proof></div>
    <details className={s.raw}><summary>Inspect public channel record</summary><pre>{JSON.stringify(channel, null, 2)}</pre></details>
  </>;
}
function Specimen({ sample }: { sample: PublicRecord }) {
  const creative = object(sample.creative ?? sample.sponsored), decision = object(sample.decision), receipt = object(sample.receipt), evidence = object(sample.evidence);
  return <><div className={s.inspectHeading}><span>Actual output</span><span>{short(sample.turnId)}</span></div><h3>{str(sample.prompt ?? sample.question, 'Recorded publisher turn')}</h3>
    {str(sample.answer) && <div className={s.answer}><span>Independent answer · DeepSeek</span><p>{str(sample.answer)}</p></div>}
    {Object.keys(creative).length > 0 && <div className={s.sponsored}><span>Sponsored</span><h4>{str(creative.title ?? creative.headline)}</h4><p>{str(creative.body ?? creative.text)}</p><span>{str(creative.cta ?? creative.ctaLabel)}{str(creative.advertiserName) && ` · ${str(creative.advertiserName)}`}</span></div>}
    <div className={s.decision}><span>Jev buying decision</span><strong>{str(decision.action ?? decision.verdict, 'Recorded decision').replaceAll('_', ' ')}</strong>{str(decision.reason) && <p>{str(decision.reason)}</p>}</div>
    {Object.keys(receipt).length > 0 && <div className={s.receipt}><span>Accepted insertion receipt</span><strong>{short(receipt.hash ?? receipt.receiptHash ?? receipt.id)}</strong><span>{receipt.sponsoredLabelPresent === true ? 'Sponsored disclosure recorded' : 'Disclosure status unavailable'}</span></div>}
    <details className={s.raw}><summary>Inspect evidence and public turn record</summary>{sample.authoredHints != null && <><h4>Advertiser authored hints</h4><pre>{JSON.stringify(sample.authoredHints, null, 2)}</pre></>}{Object.keys(evidence).length > 0 && <><h4>Screened ContextHint evidence</h4><pre>{JSON.stringify(evidence, null, 2)}</pre></>}<pre>{JSON.stringify(sample, null, 2)}</pre></details>
  </>;
}
export default function NetworkRun({ record }: { record: unknown }) {
  const run = useMemo(() => normalize(record), [record]);
  const { actual, measured: m, accounting: a, events, channels, campaigns } = run;
  const [cursor, setCursor] = useState(events.length ? events.length - 1 : 0);
  const [playing, setPlaying] = useState(false);
  const [scrubbed, setScrubbed] = useState(false);
  const [selected, setSelected] = useState(channels[0]?.id ?? '');
  const current = events[cursor];
  const activeCampaign = current?.campaignId;
  const scopes = useMemo(() => [...new Set(campaigns.map(c => c.scope))], [campaigns]);
  const selectedChannel = channels.find(c => c.id === selected) ?? channels[0];
  const sample = selectedChannel ? run.specimens.find(v => v.channelId === selectedChannel.id || v.campaignId === selectedChannel.campaignId) : run.specimens[0];
  const completed = run.status === 'completed';
  const phase = /voucher|authoriz/.test(current?.type ?? '') ? 'voucher' : /settle|close|refund/.test(current?.type ?? '') ? 'chain' : /receipt|deliver|accept/.test(current?.type ?? '') ? 'delivery' : /auction|bid|award/.test(current?.type ?? '') ? 'auction' : 'decision';
  useEffect(() => {
    if (!playing || !events.length) return;
    const timer = setInterval(() => setCursor(c => { if (c >= events.length - 1) { setPlaying(false); return c; } return Math.min(events.length - 1, c + Math.max(1, Math.ceil(events.length / 160))); }), 250);
    return () => clearInterval(timer);
  }, [playing, events.length]);
  const selectCampaign = (id: string) => { const c = campaigns.find(c => c.id === id); const ch = channels.find(ch => ch.id === c?.channelId || ch.campaignId === id); if (ch) setSelected(ch.id); };
  const date = actual && run.date ? new Date(run.date).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' }) : '';
  const native = num(m.nativeTransactions);
  const vouchers = num(m.voucherUpdates);
  const ratio = native > 0 ? vouchers / native : 0;
  const provider = object(a.provider);
  const spend = Object.values(provider).reduce<number>((sum, v) => sum + num(object(v).knownUsd), 0);
  return <>
    <section className={s.intro} aria-labelledby="network-title"><div className={s.statusLine}><span className={s.status} data-actual={actual}>◎ {actual ? 'Measured Devnet run' : 'Run not executed'}</span><span>{actual ? `${completed ? 'Completed' : run.status === 'partial' ? 'Partial result' : 'Recorded checkpoint'}${date ? ` · ${date}` : ''}` : 'Awaiting a recorded result'}</span></div><h1 id="network-title">A network of agents.<br /><em>One exchange.</em></h1><p>Each accepted insertion advances an off-chain total. Solana channels settle it in batches.</p></section>
    <div className={s.topline} aria-label={actual ? 'Measured whole-run totals' : 'No measured results yet'}><Stat value={actual ? m.fundedAdvertisers : null} label="Funded advertisers" detail="Fictional test campaigns" /><Stat value={actual ? m.publisherTurnsAttempted : null} label="Publisher turns" detail="Fresh recorded attempts" /><Stat value={actual ? m.jevAttempts : null} label="Jev decisions attempted" /><Stat value={actual ? m.acceptedDeliveries : null} label="Accepted insertions" /><Stat value={actual ? m.finalizedTransactions : null} label="Finalized native transactions" /></div>
    <section className={s.stage} aria-labelledby="stage-title" data-phase={playing || scrubbed ? phase : 'all'}>
      <div className={s.stageHeading}><h2 id="stage-title">The whole network.</h2><span>{actual ? '◎ Recorded replay · whole-run totals' : 'No model calls or payments recorded'}</span></div>
      <div className={s.network}>
        <div className={s.campaigns}><div className={s.columnHeading}><span>Advertiser agents</span><strong>{actual ? count(m.fundedAdvertisers) : '·'}</strong></div>{actual && campaigns.length ? <div className={s.clusters}>{scopes.map(scope => <div className={s.cluster} key={scope}><div><span>{scope.replace(/^worker[-_]/, 'Cohort ').replaceAll('_', ' ')}</span><small>{campaigns.filter(c => c.scope === scope).length}</small></div><div className={s.nodes}>{campaigns.filter(c => c.scope === scope).map(c => <button key={c.id} className={s.node} data-filled={c.acceptedDeliveries > 0} data-funded={c.funded} data-active={activeCampaign === c.id && (playing || scrubbed)} data-selected={selectedChannel?.campaignId === c.id} onClick={() => selectCampaign(c.id)} aria-label={`${c.name}, ${c.scope}, ${c.funded ? 'funded' : 'not funded'}, ${c.acceptedDeliveries} accepted deliveries`} title={`${c.name} · ${c.acceptedDeliveries} accepted deliveries`} />)}</div></div>)}</div> : <div className={s.emptyField}><span>□</span><p>{actual ? 'Campaign records unavailable' : 'Funded campaign nodes appear here after execution.'}</p></div>}<div className={s.legend}><span><i /> Funded</span><span><i data-filled="true" /> Accepted delivery</span></div></div>
        <div className={s.pipeline}><div className={s.flowStep} data-step="decision"><span>Jev</span><strong>{actual ? count(m.validDecisions) : '·'}</strong><small>Valid buying decisions</small></div><span className={s.flowArrow}>↓</span><div className={s.flowStep} data-step="auction"><span>Eligible auction</span><strong>{actual ? count(m.bids) : '·'}</strong><small>Admitted bids</small></div><span className={s.flowArrow}>↓</span><div className={s.flowStep} data-step="delivery"><span>Sponsored</span><strong>{actual ? count(m.acceptedDeliveries) : '·'}</strong><small>Accepted insertion receipts</small></div><div className={s.noFill}>{actual ? count(m.noFill) : '·'} no-fill turns · answer remains independent</div></div>
        <div className={s.channels}><div className={s.columnHeading}><span>Payment channels</span><strong>{actual ? count(channels.length) : '·'}</strong></div>{actual && channels.length ? <div className={s.channelNodes}>{channels.map(ch => <button key={ch.id} data-settled={ch.paymentPhase === 'settled' || ch.paymentPhase === 'closed'} data-selected={ch.id === selectedChannel?.id} onClick={() => setSelected(ch.id)} aria-label={`${ch.name || short(ch.id)}, ${ch.paymentPhase}, ${usdc(ch.settledBaseUnits)} test USDC settled`} title={`${ch.name || short(ch.id)} · ${ch.paymentPhase}`}><i style={{height: `${ch.depositBaseUnits ? Math.min(100, ch.acceptedBaseUnits / ch.depositBaseUnits * 100) : 0}%`}} /></button>)}</div> : <div className={s.emptyField}><span>▯</span><p>{actual ? 'Channel records unavailable' : 'Each recorded channel keeps its cumulative payment total.'}</p></div>}<div className={s.legend}><span><i data-bar="true" /> Cumulative accepted amount</span></div><div className={s.channelTotal}><strong>{actual ? usdc(a.settledBaseUnits) : '·'} <small>test USDC</small></strong><span>Finalized publisher payout</span></div></div>
      </div>
      <div className={s.paymentLanes}><div className={s.offChain} data-step="voucher"><span>Off-chain</span><div className={s.voucherLine}>{Array.from({length: 28}, (_, i) => <i key={i} data-shown={actual && vouchers > 0} />)}</div><strong>{actual ? count(vouchers) : '·'}</strong><span>Cumulative voucher updates</span></div><div className={s.onChain} data-step="chain"><span>Solana Devnet</span><div className={s.chainSteps}><span>Deposit</span><i /><span>Settle + refund</span></div><strong>{actual ? count(native) : '·'}</strong><span>Native transactions</span></div></div>
      <div className={s.playback}><button onClick={() => { if (!playing && cursor >= events.length - 1) setCursor(0); setScrubbed(true); setPlaying(p => !p); }} disabled={!events.length} aria-label={playing ? 'Pause recorded replay' : 'Replay recorded run'}>{playing ? 'Ⅱ Pause' : '▷ Replay recorded run'}</button><button className={s.stepControl} disabled={!events.length || cursor === 0} aria-label="Previous recorded event" onClick={() => { setPlaying(false); setScrubbed(true); setCursor(c => Math.max(0, c - 1)); }}>←</button><input aria-label="Recorded event timeline" type="range" min={0} max={Math.max(0, events.length - 1)} value={cursor} disabled={!events.length} onChange={e => {setPlaying(false); setScrubbed(true); setCursor(Number(e.target.value));}} /><button className={s.stepControl} disabled={!events.length || cursor >= events.length - 1} aria-label="Next recorded event" onClick={() => { setPlaying(false); setScrubbed(true); setCursor(c => Math.min(events.length - 1, c + 1)); }}>→</button><span>{events.length ? `${count(cursor + 1)} / ${count(events.length)}` : 'No recorded events'}</span></div>
      {current && <div className={s.currentEvent}><span>{current.type.replaceAll('_', ' ')}</span><span>{short(current.turnId || current.channelId)}</span><span>{current.status.replaceAll('_', ' ')}</span></div>}
    </section>
    <div className={s.caption}><p>{actual ? 'Every node is a fictional test advertiser. Select a campaign or channel to inspect its recorded proof.' : 'The diagram will be populated from the actual run. No target counts are presented as measured outcomes.'}</p>{actual && native > 0 && <p><strong>{ratio.toLocaleString('en-US', {maximumFractionDigits: 1})}</strong> off-chain voucher updates per native transaction.</p>}</div>
    <section className={s.inspection} aria-labelledby="inspect-title"><div className={s.sectionHeading}><h2 id="inspect-title">Follow one payment.</h2><span>Insertion → receipt → authorization → settlement</span></div>{actual ? <div className={s.inspectGrid}><article className={s.turn}>{sample ? <Specimen sample={sample} /> : <><span className={s.inspectHeading}>Actual turn specimen</span><h3>No public specimen recorded.</h3><p>The measured totals remain available above.</p></>}</article><article className={s.channel}>{selectedChannel ? <ChannelProof channel={selectedChannel} /> : <p>No channel evidence recorded.</p>}</article></div> : <div className={s.emptyInspection}><span>◎</span><div><h3>Nothing to replay yet.</h3><p>Actual answers, buying decisions, receipts and public Devnet proof will appear after the run is recorded.</p></div></div>}</section>
    {actual && <details className={s.runDetails}><summary>Inspect measured run record</summary><div className={s.detailsGrid}><div><h3>Execution</h3><dl><dt>Answers completed</dt><dd>{count(m.answersCompleted)}</dd><dt>Valid decisions</dt><dd>{count(m.validDecisions)}</dd><dt>Skips / abstentions</dt><dd>{count(m.skips)} / {count(m.abstentions)}</dd><dt>Errors</dt><dd>{count(m.errors)}</dd><dt>Peak publisher concurrency</dt><dd>{count(m.peakPublisherConcurrency)}</dd><dt>Peak Jev concurrency</dt><dd>{count(m.peakJevConcurrency)}</dd></dl></div><div><h3>Separate accounting</h3><dl><dt>Accepted</dt><dd>{usdc(a.acceptedBaseUnits)} test USDC</dd><dt>Authorized</dt><dd>{usdc(a.authorizedBaseUnits)} test USDC</dd><dt>Settled</dt><dd>{usdc(a.settledBaseUnits)} test USDC</dd><dt>Refunded</dt><dd>{usdc(a.refundBaseUnits)} test USDC</dd><dt>API usage cost upper bound</dt><dd>${spend.toFixed(4)}</dd><dt>Unknown provider attempts</dt><dd>{count(Object.values(provider).reduce<number>((sum, v) => sum + num(object(v).unknownAttempts), 0))}</dd><dt>Network fees</dt><dd>{(num(a.networkFeeLamports) / 1e9).toFixed(6)} Devnet SOL</dd></dl></div></div>{run.limitations.map((v, i) => <p key={i}>{v}</p>)}<details className={s.raw}><summary>Public JSON record</summary><pre>{JSON.stringify(run.raw, null, 2)}</pre></details></details>}
    <footer className={s.footer}><p>DeepSeek writes the example answer. Jev judges buying fit. Screened ContextHint evidence is separate from advertiser authored hints.</p><div><span>Solana Devnet · test USDC · recorded replay</span><ActionText href="/publisher-demo/">Open the example chat</ActionText></div></footer>
  </>;
}
