import {acknowledgePlacement} from '/publisher.mjs';
const $=id=>document.getElementById(id),node=(tag,copy,cls)=>{const n=document.createElement(tag);if(copy!==undefined)n.textContent=copy;if(cls)n.className=cls;return n;};
const form=$('draft-form'),selected=new Set();let csrf='',bootstrap,state,step=0,draftId=null,lastTurn=null,currentAward=null,busy=false,conversation=crypto.randomUUID();
const value=name=>form.elements.namedItem(name).value;
const amount=s=>{if(!/^\d+(\.\d{1,6})?$/.test(s))throw Error('Use a positive amount with at most 6 decimal places.');const [a,b='']=s.split('.');return (BigInt(a)*1000000n+BigInt(b.padEnd(6,'0'))).toString();};
const money=x=>`${(BigInt(x??'0')/1000000n).toString()}.${(BigInt(x??'0')%1000000n).toString().padStart(6,'0')} test USDC`;
const notify=s=>{$('notice').textContent=s;};
async function get(path){const r=await fetch(path);const data=await r.json();if(!r.ok)throw Error(data.error??'Request failed');return data;}
async function post(path,data={}){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-AXP-CSRF':csrf},body:JSON.stringify(data)});const result=await r.json();if(!r.ok)throw Error(result.error??'Request failed');return result;}
function route(){const name=location.hash.slice(1)||'setup';for(const p of document.querySelectorAll('.page'))p.hidden=p.id!==name;for(const a of document.querySelectorAll('nav a')){if(a.hash===`#${name}`)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');}if(!document.getElementById(name))location.hash='campaigns';}
window.addEventListener('hashchange',route);
$('matching-form').onsubmit=async ev=>{
  ev.preventDefault();const button=ev.currentTarget.querySelector('button');button.disabled=true;
  try{
    const r=await post('/v1/advertiser/compare',{campaignId:$('matching-campaign').value,prompt:$('matching-prompt').value});
    $('matching-results').replaceChildren();
    for(const [label,arm] of [['Approved text only',r.baseline],['Text + ContextHint history',r.history]]){
      const a=node('article',undefined,'panel'),p=arm.decision.engineProvenance;
      a.append(node('h2',label),node('p',`Candidate: ${arm.decision.decision} · relevance ${arm.decision.relevanceLevel} / 3`),node('p',`Executable simulated bid: ${arm.bid.status==='bid'?money(arm.bid.amountBaseUnits):'none — '+arm.bid.reason}`),node('p',`Text support ${Math.round(p.textCoverage*100)}% · effective support ${Math.round(p.effectiveCoverage*100)}%`),node('p',`${p.supportingHistoricalEvidenceIds.length} aligned historical records. ${p.fallbackReason??'No product-performance inference.'}`));
      $('matching-results').append(a);
    }
    $('matching-status').textContent=`${r.changed?'Decision or bid changed.':'No decision or bid change.'} ${r.fundingEligibility.eligible?'':'Funding unavailable: '+r.fundingEligibility.reason+'. '}Comparison only: no auction, charge, model call or payment. A change is not proven targeting improvement.`;
    evidenceCards(r.history.decision.engineProvenance.retrieval.selected,$('matching-evidence'),false);
    $('matching-trace').textContent=JSON.stringify(r,null,2);notify('Nonfinancial comparison completed. Existing placements and charges are unchanged.');
  }catch(e){$('matching-status').textContent=e.message;}finally{button.disabled=false;}
};
function draftInput(){return {...(draftId?{draftId}:{}),name:value('name'),brandName:value('brandName'),websiteURL:value('websiteURL'),productDescription:value('productDescription'),approvedText:value('approvedText'),contextHints:value('contextHints').split('\n').map(x=>x.trim()).filter(Boolean),declaredCapabilities:[...document.querySelectorAll('#capabilities input:checked')].map(x=>x.value),evidenceIds:[...selected],maxBidBaseUnits:amount(value('maxBid')),budgetCapBaseUnits:amount(value('budget')),depositBaseUnits:amount(value('deposit')),approved:form.elements.namedItem('approved').checked};}
async function save(){const d=await post('/v1/advertiser/drafts',draftInput());draftId=d.draftId;await refresh();return d;}
function showStep(n){step=Math.max(0,Math.min(4,n));for(const p of document.querySelectorAll('[data-panel]'))p.hidden=Number(p.dataset.panel)!==step;for(const b of document.querySelectorAll('[data-step]')){if(Number(b.dataset.step)===step)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');}$('back').disabled=step===0;$('next').hidden=step===4;creativePreview();if(step===4){$('review').replaceChildren();for(const [name,copy] of [['Campaign',value('name')],['Advertiser',`${value('brandName')} · fictional`],['Ad',value('approvedText')],['Context hints',value('contextHints')],['Evidence',`${selected.size} historical references`],['Maximum bid',value('maxBid')+' test USDC'],['Campaign cap',value('budget')+' test USDC'],['Simulated deposit',value('deposit')+' test USDC']]){const p=node('p');p.append(node('strong',`${name}: `),node('span',copy));$('review').append(p);}}}
function creativePreview(){const p=$('creative-preview');p.replaceChildren(node('strong','Sponsored'),node('p',`${value('brandName')}: ${value('approvedText')}`),node('small','Fictional advertiser declaration · separate from the organic answer'));}
function syncEvidenceSelection(){for(const cb of document.querySelectorAll('#wizard-evidence input[data-evidence-id]'))cb.checked=selected.has(cb.dataset.evidenceId);$('selection-count').textContent=`${selected.size} evidence records selected`;}
for(const b of document.querySelectorAll('[data-step]'))b.onclick=()=>showStep(Number(b.dataset.step));$('back').onclick=()=>showStep(step-1);$('next').onclick=()=>showStep(step+1);form.oninput=ev=>{if(ev.target.name!=='approved')form.elements.namedItem('approved').checked=false;creativePreview();};
$('save-draft').onclick=async()=>{try{await save();notify('Draft saved locally. No campaign activated or budget reserved.');}catch(e){notify(e.message);}};
$('account-form').onsubmit=async ev=>{ev.preventDefault();try{const a=Object.fromEntries(new FormData(ev.currentTarget));await post('/v1/advertiser/account',a);await refresh();notify('Demo business saved. No real advertiser enrollment.');location.hash='create';}catch(e){notify(e.message);}};
form.onsubmit=async ev=>{ev.preventDefault();if(busy)return;busy=true;try{if(!state.account)throw Error('Save your business setup first.');if(!form.elements.namedItem('approved').checked)throw Error('Approve your fictional creative and declarations before launch.');const d=await save();await post(`/v1/advertiser/drafts/${d.draftId}/launch`);notify('Campaign launched in simulation. No actual funds deposited.');draftId=null;await refresh();location.hash='campaigns';}catch(e){notify(e.message);}finally{busy=false;}};
$('preview-button').onclick=async()=>{try{const d=await save();const r=await post('/v1/advertiser/preview',{draftId:d.draftId,prompt:$('preview-prompt').value});$('preview-result').textContent=JSON.stringify(r,null,2);notify('Preview only: zero opportunity, reservation or charge created.');}catch(e){notify(e.message);}};
function loadDraft(d){draftId=d.draftId;for(const k of ['name','brandName','websiteURL','productDescription','approvedText'])form.elements.namedItem(k).value=d[k];form.elements.namedItem('contextHints').value=d.contextHints.join('\n');form.elements.namedItem('approved').checked=d.approved;for(const [key,field] of [['maxBidBaseUnits','maxBid'],['budgetCapBaseUnits','budget'],['depositBaseUnits','deposit']])form.elements.namedItem(field).value=money(d[key]).split(' ')[0];for(const c of document.querySelectorAll('#capabilities input'))c.checked=d.declaredCapabilities.includes(c.value);selected.clear();d.evidenceIds.forEach(x=>selected.add(x));syncEvidenceSelection();showStep(0);location.hash='create';}
function evidenceCards(records,target,selectable){target.replaceChildren();if(!records.length)target.append(node('p','No matching records in this bounded export. Try “travel”, “agent” or “hotel”. No fabricated results.'));for(const r of records){const a=node('article');a.append(node('span','Observed association','tag'),node('h2',r.advertiser),node('p',`Prompt ${r.promptId}: ${r.promptText}`),node('p',r.creativeText??'Original creative copy unavailable in this recorded excerpt.'),node('p',`Creative ${r.creativeId} · mapping ${r.mappingId}`));if(r.hint)a.append(node('span','Inferred hint','tag'),node('p',r.hint.text),node('p',`${r.hint.tier??'unknown'} · ${r.hint.modelVersion??'unknown'}`));if(selectable){const label=node('label',undefined,'check select'),cb=node('input');cb.type='checkbox';cb.dataset.evidenceId=r.id;cb.checked=selected.has(r.id);cb.setAttribute('aria-label',`Select evidence ${r.id}`);cb.onchange=()=>{if(cb.checked&&selected.size>=12){cb.checked=false;notify('Select at most 12 evidence records.');return;}cb.checked?selected.add(r.id):selected.delete(r.id);form.elements.namedItem('approved').checked=false;$('selection-count').textContent=`${selected.size} evidence records selected`;};label.append(cb,node('span','Attach as a historical reference'));a.prepend(label);if(r.hint){const use=node('button','Use inferred hint as editable starting point');use.type='button';use.onclick=()=>{const hints=value('contextHints').split('\n').map(x=>x.trim()).filter(Boolean);if(!hints.includes(r.hint.text)){if(hints.length>=6){notify('Use at most six context hints. Edit your existing wording first.');return;}hints.push(r.hint.text);}form.elements.namedItem('contextHints').value=hints.join('\n');form.elements.namedItem('approved').checked=false;notify('Inferred hypothesis copied to your draft. Edit and approve it; it is not verified targeting.');};a.append(use);}}a.append(node('small','Historical brand, not an AXP participant.'));target.append(a);}}
async function search(query,target,selectable){const r=await get(`/v1/advertiser/evidence?q=${encodeURIComponent(query)}`);evidenceCards(r.records,target,selectable);}
$('wizard-search').onclick=()=>search($('wizard-query').value,$('wizard-evidence'),true).catch(e=>notify(e.message));$('evidence-form').onsubmit=ev=>{ev.preventDefault();search(new FormData(ev.currentTarget).get('query'),$('library'),false).catch(e=>notify(e.message));};
function drawCampaigns(){const totals=state.summaries.reduce((a,s)=>({accepted:a.accepted+BigInt(s.acceptedBaseUnits),reserved:a.reserved+BigInt(s.reservedBaseUnits),deliveries:a.deliveries+s.deliveries}),{accepted:0n,reserved:0n,deliveries:0});$('summary').replaceChildren();for(const [copy,n] of [['Active campaigns',state.campaigns.filter(c=>c.status==='active').length],['Accepted simulated spend',money(totals.accepted.toString())],['Accepted deliveries',totals.deliveries]]){const a=node('article');a.append(node('strong',String(n)),node('span',copy));$('summary').append(a);}$('campaign-rows').replaceChildren();$('campaign-empty').hidden=state.campaigns.length>0;for(const c of state.campaigns){const d=state.campaignDetails.find(x=>x.campaignId===c.campaignId),s=state.summaries.find(x=>x.campaignId===c.campaignId),tr=node('tr');const funding=state.channels.find(x=>x.channelId===c.channelId);for(const copy of [d.name,c.status,funding.status,money(c.maxBidBaseUnits),money(s.acceptedBaseUnits),money(s.availableBaseUnits),String(s.deliveries)])tr.append(node('td',copy));const td=node('td'),b=node('button',c.status==='active'?'Pause':'Activate');b.onclick=async()=>{try{await post('/v1/advertiser/campaign-status',{campaignId:c.campaignId,status:c.status==='active'?'paused':'active'});await refresh();}catch(e){notify(e.message);}};td.append(b);tr.append(td);$('campaign-rows').append(tr);}$('campaign-detail').replaceChildren();for(const d of state.campaignDetails){const block=node('article');block.append(node('h2',d.name),node('p',`${d.brandName} · fictional advertiser · ${d.approvedText}`),node('p',`Context hints: ${d.contextHints.join(' / ')}`),node('p',`Declared hard capabilities: ${d.declaredCapabilities.join(', ')}`),node('p',`${d.evidenceIds.length} attached ContextHint references · evidence-informed simulated buyer · ${d.campaignId}`));$('campaign-detail').append(block);}}
function drawAccounting(){$('channel-cards').replaceChildren();for(const c of state.channels){const a=node('article'),s=state.summaries.find(x=>state.campaigns.find(ca=>ca.campaignId===x.campaignId)?.channelId===c.channelId);a.append(node('h2',state.campaignDetails.find(x=>state.campaigns.find(ca=>ca.campaignId===x.campaignId)?.channelId===c.channelId)?.name??c.channelId),node('span',`Synthetic · ${c.status}`,'tag'));for(const [label,v] of [['Deposit',c.depositBaseUnits],['Reserved',s?.reservedBaseUnits],['Accepted spend',s?.acceptedBaseUnits],['Cumulative authorized',c.authorizedBaseUnits],['Settled',c.settledBaseUnits],['Unused refund',c.refundBaseUnits]])a.append(node('p',`${label}: ${money(v)}`));const actions=node('div',undefined,'actions');for(const [label,action] of [['Authorize accepted total','authorize'],['Settle & refund','close']]){const b=node('button',label);b.disabled=c.status==='finalized';b.onclick=async()=>{try{await post(`/v1/advertiser/channels/${c.channelId}/${action}`);await refresh();notify(`${action==='close'?'Settlement/refund':'Cumulative authorization'} simulated. No wallet or native voucher used.`);}catch(e){notify(e.message);}};actions.append(b);}a.append(actions);$('channel-cards').append(a);}$('charges').replaceChildren();for(const c of state.charges){const tr=node('tr');for(const s of [c.id,c.campaignId,money(c.amountBaseUnits),c.status,c.receiptHash.slice(0,16)+'…'])tr.append(node('td',s));$('charges').append(tr);}$('events').replaceChildren();for(const e of state.events.slice(-30).reverse())$('events').append(node('li',`${e.seq} · ${e.type} · ${JSON.stringify(e.data)}`));}
async function refresh(){state=await get('/v1/advertiser/state');drawCampaigns();drawAccounting();const prior=$('matching-campaign').value;$('matching-campaign').replaceChildren();for(const c of state.campaigns){const d=state.campaignDetails.find(x=>x.campaignId===c.campaignId),option=node('option',`${d.brandName} — fictional`);option.value=c.campaignId;$('matching-campaign').append(option);}if(state.campaigns.some(c=>c.campaignId===prior))$('matching-campaign').value=prior;$('saved-drafts').replaceChildren(node('h2','Saved drafts'));for(const d of state.drafts.filter(d=>!d.launchedCampaignId)){const b=node('button',`Continue ${d.name}`);b.onclick=()=>loadDraft(d);$('saved-drafts').append(b);}}
async function execute(input){busy=true;$('turn-form').querySelector('button').disabled=true;currentAward=null;$('ad').hidden=true;$('delivery-status').textContent='Evaluating simulated buyers…';try{const r=await post('/v1/advertiser/turn',input);$('organic').textContent=`Deterministic reference answer (not an LLM): ${r.organic.text}`;$('trace').textContent=JSON.stringify(r,null,2);$('decisions').replaceChildren();for(const a of r.attempts){const c=state.campaigns.find(c=>c.campaignId===a.campaignId),d=state.campaignDetails.find(d=>d.campaignId===a.campaignId),p=node('p');p.append(node('strong',`${d?.brandName??a.campaignId}: ${a.decision?.decision??a.status}`),node('span',` · fit ${a.decision?.relevanceLevel??'?'} / 3 · ${a.decision?.reasonCodes.join(', ')??a.reason}`));$('decisions').append(p);const evidence=a.decision?.engineProvenance;if(evidence?.engineVersion){$('decisions').append(node('p',`ContextHint: ${evidence.supportingHistoricalEvidenceIds.length} aligned records · text support ${Math.round(evidence.textCoverage*100)}% → combined support ${Math.round(evidence.effectiveCoverage*100)}%. ${evidence.fallbackReason??'Historical relevance prior used; not verified product performance.'}`));}}for(const x of r.eligibility.excluded)$('decisions').append(node('p',`${state.campaignDetails.find(d=>d.campaignId===x.campaignId)?.brandName??x.campaignId}: excluded — ${x.reason}`));for(const bid of r.outcome.bids)$('decisions').append(node('p',`Executable bid: ${state.campaignDetails.find(d=>d.campaignId===bid.campaignId)?.brandName??bid.campaignId} · ${money(bid.amountBaseUnits)} · integer score-band policy`));
  const award=r.outcome.award;if(!award||!['reserved','delivered'].includes(award.status)){$('delivery-status').textContent=`${r.outcome.status} · no new charge.`;}else{currentAward=award;const mode=$('delivery-mode').value;if(mode==='fail'&&award.status==='reserved'){await post(`/v1/awards/${award.id}/fail`);$('delivery-status').textContent='Delivery failed. Reservation released; zero charge.';}else if(mode==='hold'&&award.status==='reserved'){$('delivery-status').textContent='Award reserved but not delivered. No charge. It expires after three minutes.';const b=node('button','Fail held award & release reservation');b.onclick=async()=>{try{await post(`/v1/awards/${award.id}/fail`);await refresh();$('delivery-status').textContent='Held award failed. Zero charge.';}catch(e){notify(e.message);}};$('delivery-status').append(b);}else{const ad=$('ad');ad.replaceChildren();ad.dataset.awardId=award.id;const label=node('strong','Sponsored');label.dataset.sponsoredLabel='';const copy=node('p',award.creative.approvedText);copy.dataset.creativeCopy='';const link=node('a','Fictional advertiser website');link.href=award.creative.destinationURL;link.target='_blank';link.rel='noopener';ad.append(label,copy,link,node('small','Fictional declarations · synthetic charge · no attention or endorsement claim'));ad.hidden=false;await new Promise(requestAnimationFrame);const receipt=await acknowledgePlacement({node:ad,award,post});$('delivery-status').textContent=`${receipt.replayed?'Existing receipt replayed — no new charge.':'Browser insertion and disclosure accepted.'} ${money(receipt.charge.amountBaseUnits)} · receipt ${receipt.charge.receiptHash.slice(0,12)}…`;}}
  await refresh();notify(r.replayed?'Same turn replayed. No second auction or charge.':'Simulation completed. No model provider or blockchain was called.');}catch(e){notify(e.message);}finally{busy=false;$('turn-form').querySelector('button').disabled=false;$('retry').disabled=!lastTurn;}}
$('turn-form').onsubmit=ev=>{ev.preventDefault();if(busy)return;lastTurn={prompt:$('question').value,turnId:crypto.randomUUID(),randomSessionId:conversation};execute(lastTurn);};$('retry').onclick=()=>{if(lastTurn&&!busy)execute(lastTurn);};$('new-conversation').onclick=()=>{if(busy)return;conversation=crypto.randomUUID();lastTurn=null;$('retry').disabled=true;notify('New conversation: a fresh frequency-cap scope. Existing charges and budgets remain.');};for(const b of document.querySelectorAll('[data-question]'))b.onclick=()=>{$('question').value=b.dataset.question;};
bootstrap=await get('/v1/advertiser/bootstrap');csrf=bootstrap.csrf;for(const c of bootstrap.capabilities){const label=node('label',undefined,'check'),cb=node('input');cb.type='checkbox';cb.value=c;cb.checked=['travel_booking','expense_management','policy_enforcement'].includes(c);label.append(cb,node('span',c.replaceAll('_',' ')));$('capabilities').append(label);}for(const p of bootstrap.presets){const opt=node('option',`${p.brandName} — fictional`);opt.value=p.id;$('preset').append(opt);}$('preset').value='tripdesk';$('preset').onchange=()=>{const p=bootstrap.presets.find(p=>p.id===$('preset').value);draftId=null;selected.clear();syncEvidenceSelection();form.elements.namedItem('approved').checked=false;if(!p)return;for(const k of ['name','brandName','websiteURL','productDescription','approvedText'])form.elements.namedItem(k).value=p[k];form.elements.namedItem('contextHints').value=p.contextHints.join('\n');for(const c of document.querySelectorAll('#capabilities input'))c.checked=p.declaredCapabilities.includes(c.value);$('selection-count').textContent='0 evidence records selected';showStep(0);};
$('evidence-source').append(node('p',`${bootstrap.evidence.records} records · ${bootstrap.evidence.sourceMode} · captured ${bootstrap.evidence.capturedAt}`),node('p',`Content hash: ${bootstrap.evidence.contentHash}`),node('p',bootstrap.evidence.limitations.join(' ')));if(bootstrap.evidence.inventory)$('evidence-source').append(node('pre',JSON.stringify(bootstrap.evidence.inventory,null,2)));
await refresh();if(!location.hash)location.hash=state.account?'campaigns':'setup';route();showStep(0);await search('', $('wizard-evidence'),true);await search('', $('library'),false);
