import {acknowledgePlacement} from '/publisher.mjs';
const $=s=>document.querySelector(s),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const steps=['foundation','onboarding','retrieval','decisions','publisher','accounting','payment','limits'];
const captions=[
 'AXP uses real conversational-ad observations to inform advertiser-agent placement decisions. Historical brands are references, not enrolled advertisers.',
 'Create a fictional campaign with independent creative, targeting declarations and capped synthetic spending. Historical hints are hypotheses, not advertiser declarations.',
 'The exact cached question uses existing prompt vectors. The uncached question uses labelled lexical fallback. No embeddings are generated.',
 'Twelve planned paired slots: text-only and history arms. Ten actual Jev responses; two history slots unavailable. Only history outputs enter auctions. Code calculates money.',
 'An organic deterministic reference stays separate from the Sponsored card. Only an accepted owned-app delivery acknowledgement creates a charge.',
 'V2 deposits, reservations, charges, authorizations and final synthetic amounts are distinct. There is no token transfer for these crypto placements.',
 'Separate V1 recorded payment: actual MPP settlement on the hosted Solana sandbox, not Devnet. It did not pay for V2 crypto placements.',
 'This is a small paired demonstration, not targeting accuracy, ChatGPT algorithm reconstruction, human attention or conversion lift.'
];
let boot,state,catalogue,selected=0,busy=false;
const request=async(path,body)=>{const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','x-axp-csrf':boot.csrf},body:JSON.stringify(body)}),v=await r.json();if(!r.ok)throw Error(v.error??'request_failed');return v;};
const pre=value=>{
 let summary='';
 if(value?.promptText)summary=`<p><strong>Observed prompt:</strong> ${escape(value.promptText)}</p><p><strong>Observed creative:</strong> ${escape(value.creativeText)}</p><small>Source mapping ${escape(value.mappingId)} · creative ${escape(value.creativeId)} · historical association, not a fit label</small>`;
 if(value?.method&&Array.isArray(value.examples))summary=`<p>Source ${escape(value.sourceHash.slice(0,16))}… · ${value.examples.length} aligned examples · ${value.hints.length} inferred hints · ${value.fallback?'lexical fallback':'no fallback'}</p>${value.examples.slice(0,2).map(x=>`<p>${escape(x.text)}</p>`).join('')}${value.hints.slice(0,1).map(h=>`<p><strong>Inferred hint:</strong> ${escape(h.text)}</p>`).join('')}`;
 if(value?.plannedCalls!==undefined)summary=`<p><strong>${value.completedCalls} actual completed calls</strong> / ${value.plannedCalls} planned slots · ${value.unavailableCalls} unavailable · ${value.remainingCalls} unused allowance · ${value.failedCalls} failures · ${value.uncertainCalls} uncertain</p>`;
 return summary+`<details><summary>Inspect full evidence and identifiers</summary><pre>${escape(JSON.stringify(value,null,2))}</pre></details>`;
};
const money=n=>(Number(n??0)/1e6).toFixed(6);
const name=id=>boot.names[id]??id;
const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${escape(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
async function refresh(){state=await request('/v2/state');$('#mode').textContent=`V2 · SYNTHETIC accounting · ${boot.replay?'RECORDED REPLAY':'interactive reference'}`;$('#execution').textContent=boot.replay?`Read-only · zero new calls · ${state.runId} · ${new Date(state.completed.at).toISOString()}`:state.modelEnabled?'Actual Jev operator-enabled':'Preview only · models disabled';}
function notice(s){$('#notice').textContent=s;}
function records(){return catalogue.records??catalogue.associations??catalogue.examples??[];}
function foundation(){const m=boot.manifest;$('#view').innerHTML=`<h1>Evidence, not invented targeting</h1><p>ContextHint’s historical prompt–creative associations and inferred hints are the data foundation. The larger wallet slice is screened and frozen for this demo.</p><div class="metrics"><article><strong>${escape(m.counts?.associations??m.exportedAssociations??records().length)}</strong>exported associations</article><article><strong>${escape(m.counts?.normalizedPrompts??m.counts?.prompts??'See manifest')}</strong>distinct prompt records</article><article><strong>${escape(m.counts?.creatives??'See manifest')}</strong>observed creatives</article></div><div class="panel"><h2>Frozen export</h2>${pre(m)}</div><h2>Inspect historical observations</h2><label>Filter evidence<input id="filter" placeholder="OneKey, Mercari, hardware…"></label><div id="historical"></div>`;const show=()=>{const f=$('#filter').value.toLowerCase(),rs=records().filter(r=>JSON.stringify(r).toLowerCase().includes(f)).slice(0,6);$('#historical').innerHTML=rs.map(r=>`<article><span class="tag">Historical observation · not enrolled</span>${pre(r)}</article>`).join('')||'<p>No matching exported record.</p>';};$('#filter').oninput=show;show();}
function onboarding(){const ds=state.drafts;$('#view').innerHTML=`<h1>Onboard a fictional advertiser</h1><p>Declare what your own product does. Historical examples cannot add missing capabilities.</p><label>Campaign<select id="campaign">${ds.map(d=>`<option value="${escape(d.campaign.campaignId)}">${escape(name(d.campaign.campaignId))} — ${d.approved?'approved':'draft'}</option>`).join('')}</select></label><form id="form"><label>Business name<input id="business" required></label><label>Independent approved creative<textarea id="creative" required></textarea></label><label>Independent context hints<textarea id="hints" required></textarea></label><p id="capabilities"></p><p class="money">Synthetic deposit 0.020 · max bid 0.004 · total cap 0.008 test USDC</p><label class="check"><input id="approved" type="checkbox">I approve this fictional creative and these declarations</label><button id="save" ${boot.replay||state.freeze?'disabled':''}>Save and approve campaign</button></form>`;const fill=()=>{const d=ds.find(d=>d.campaign.campaignId===$('#campaign').value);$('#business').value=d.businessName;$('#creative').value=d.campaign.creatives[0].approvedText;$('#hints').value=d.contextHints;$('#approved').checked=d.approved;$('#capabilities').textContent=`Fixed declared capabilities: ${d.campaign.declaredConstraints.join(', ')}`;};$('#campaign').onchange=fill;fill();$('#form').onsubmit=async e=>{e.preventDefault();try{await request('/v2/campaign',{campaignId:$('#campaign').value,businessName:$('#business').value,creative:$('#creative').value,contextHints:$('#hints').value,approved:$('#approved').checked});await refresh();notice('Campaign saved; no provider calls or charges.');onboarding();}catch(e){notice(e.message);}};}
async function retrieval(){const ds=state.drafts;$('#view').innerHTML=`<h1>Retrieve before deciding</h1><label>Frozen question<select id="question">${boot.questions.map((q,i)=>`<option value="${i}" ${i===selected?'selected':''}>${i===0?'Cached':'Uncached'}: ${escape(q)}</option>`).join('')}</select></label><label>Own campaign<select id="retrieval-campaign">${ds.map(d=>`<option value="${escape(d.campaign.campaignId)}">${escape(name(d.campaign.campaignId))}</option>`).join('')}</select></label><div id="retrieved"></div><button id="preview" ${boot.replay?'disabled':''}>Deterministic preview · zero model calls</button><div id="preview-result"></div>`;const show=async()=>{selected=Number($('#question').value);const r=await request(`/v2/retrieval?question=${selected}&campaign=${encodeURIComponent($('#retrieval-campaign').value)}`);$('#retrieved').innerHTML=`<article><h2>${escape(r?.method??'unavailable')}</h2><p>At most five distinct prompt examples, with at most three examples and two hints in this advertiser’s compact model packet.</p>${pre(r)}</article>`;};$('#question').onchange=show;$('#retrieval-campaign').onchange=show;$('#preview').onclick=async()=>{$('#preview-result').innerHTML=pre(await request('/v2/preview',{}));};await show();}
function decisions(){const items=state.completed?.paired??[];$('#view').innerHTML=`<h1>Actual advertiser-agent bid / skip</h1><p>Financial mode: synthetic. Execution: ${escape(state.completed?.execution??'not executed')}. Remaining call allowance is persisted before invocation.</p>${pre(state.model)}<button id="run" ${boot.replay||!state.modelEnabled||busy||state.running?'disabled':''}>${state.completed?'Recover saved run · no new calls':'Run frozen paired comparison · max 12 calls'}</button><p>Own declarations and aligned evidence only; no competitors, budgets or payment tools. Only history-arm outputs drive the exchange.</p>${table(['Question / campaign','Arm','Agent output','Relevance / intent','Measured timing','Call / opportunity'],items.map(r=>[`${r.questionIndex+1} · ${escape(name(r.campaignId))}`,escape(r.arm),escape(r.decision?.decision??r.status),`${r.decision?.relevanceLevel??'—'} / ${r.decision?.commercialIntentLevel??'—'}`,`${Number(r.decision?.engineProvenance?.elapsedMs??r.elapsedMs??0).toFixed(0)} ms`,`${escape(r.callId)}<br>${escape(r.decision?.opportunityId)}`]))}<h2>Saved auction outcomes</h2>${(state.completed?.turns??[]).map(t=>`<article><h3>Question ${t.questionIndex+1}: ${escape(t.outcome.status)}</h3>${pre({opportunityId:t.opportunityId,bids:t.outcome.bids,rejections:t.outcome.rejections,policyExclusions:t.policyExclusions})}</article>`).join('')}`;$('#run').onclick=async()=>{busy=true;$('#run').disabled=true;notice('Running bounded paired decisions. Failures will be preserved; no automatic retries.');try{await request('/v2/run',{});await refresh();notice('Run saved. Model decisions are separate from auction eligibility.');await render();}catch(e){await refresh();notice(e.message);await render();}finally{busy=false;}};}
function publisher(){const turns=state.completed?.turns??[];$('#view').innerHTML=`<h1>Disclosed publisher delivery</h1><p>Owned reference publisher. Organic text is a deterministic, sponsor-free reference—not a fresh LLM answer.</p><div id="placements"></div>`;for(const t of turns){const award=state.exchange.awards.find(a=>a.opportunityId===t.opportunityId),charge=state.exchange.charges.find(c=>c.awardId===award?.id);const article=document.createElement('article');article.innerHTML=`<h2>Question ${t.questionIndex+1}</h2><p>${escape(t.task)}</p><div class="grid"><div><span class="tag">Sponsor-free deterministic reference</span><p>${escape(t.organic.text)}</p></div><div class="placement-host"></div></div><p class="status">${charge?`Accepted charge ${escape(charge.id)} · ${money(charge.amountBaseUnits)} test USDC (synthetic)`:'No accepted charge yet.'}</p>`;$('#placements').append(article);if(!award){article.querySelector('.placement-host').textContent='No fill. No charge.';continue;}const host=article.querySelector('.placement-host');const insert=()=>{const node=document.createElement('div');node.className='ad';node.dataset.awardId=award.id;node.innerHTML=`<strong data-sponsored-label>Sponsored</strong><p data-creative-copy></p><small>Fictional advertiser · declared capabilities · ${escape(name(award.campaignId))}</small>`;node.querySelector('[data-creative-copy]').textContent=award.creative.approvedText;host.replaceChildren(node);return node;};if(charge||boot.replay){insert();continue;}const button=document.createElement('button');button.textContent='Display Sponsored placement and acknowledge';button.disabled=award.status!=='reserved';button.onclick=async()=>{try{const node=insert();const result=await acknowledgePlacement({node,award,post:request});article.querySelector('.status').textContent=`Accepted receipt ${result.delivery.receiptHash} · charge ${result.charge.id} · ${money(result.charge.amountBaseUnits)} test USDC (synthetic)`;await refresh();notice('Owned-app DOM acknowledgement accepted. Not human attention or payment finality.');}catch(e){notice(e.message);}};host.append(button);}}
function accounting(){$('#view').innerHTML=`<h1>Synthetic accounting, explicitly</h1><p>No wallets, native vouchers, payment signatures or token broadcasts occur in V2. Publisher receipts are signed owned-app assertions. Auction reservations are not accepted charges.</p>${table(['Campaign','Deposit','Reserved','Accepted','Authorized','Synthetic payout / refund','Status'],state.exchange.channels.map(ch=>{const cs=state.exchange.charges.filter(c=>c.channelId===ch.channelId),reserved=state.exchange.awards.filter(a=>a.channelId===ch.channelId&&a.status==='reserved').reduce((n,a)=>n+Number(a.priceBaseUnits),0);return [escape(name(state.exchange.campaigns.find(c=>c.channelId===ch.channelId)?.campaignId)),money(ch.depositBaseUnits),money(reserved),money(cs.reduce((n,c)=>n+Number(c.amountBaseUnits),0)),money(ch.authorizedBaseUnits),`${money(ch.settledBaseUnits)} / ${money(ch.refundBaseUnits)}`,escape(ch.status)];}))}<button id="close" ${boot.replay?'disabled':''}>Authorize accepted totals and close synthetic accounting</button><h2>Receipt-linked charges</h2>${pre(state.exchange.charges)}<h2>Historical events</h2>${pre(state.exchange.events.slice(-20))}`;$('#close').onclick=async()=>{try{await request('/v2/close',{});await refresh();notice('Synthetic accounting closed. No additional charge or real payment.');accounting();}catch(e){notice(e.message);}};}
async function payment(){const v=await request('/v2/v1-payment');$('#view').innerHTML=`<h1>Separate V1 sandbox payment</h1><p><strong>Original network: hosted Solana sandbox. Presentation: recorded evidence. Not payment for V2.</strong></p><p>V1 run phase4-20261001-acceptance: deposit 0.020, publisher payout 0.006, refund 0.014 test USDC. Native MPP cumulative authorization 3000 → 6000. The sandbox may reset; saved account evidence is authoritative for this recording.</p>${pre(v)}`;}
function limits(){$('#view').innerHTML=`<h1>What this demonstrates</h1><p>Real historical evidence enters actual advertiser-agent decisions, which feed an exchange and disclosed owned-app placements.</p><ul>${state.limitations.map(l=>`<li>${escape(l)}</li>`).join('')}</ul><p>History/text differences are not causal lift: one stochastic decision per arm is insufficient. Existing vectors are not evidence of trained AXP ranking. Repeated observations do not increase retrieval relevance.</p><h2>Run identity and frozen evidence</h2>${pre({runId:state.runId,frozenAt:state.freeze?.at,completedAt:state.completed?.at,manifest:boot.manifest,bundleHash:state.bundleHash??null})}`;}
async function render(){const step=steps.includes(location.hash.slice(1))?location.hash.slice(1):'foundation',i=steps.indexOf(step);$('#caption').textContent=captions[i];$('#position').textContent=`${i+1} / ${steps.length}`;$('#previous').disabled=i===0;$('#next').disabled=i===steps.length-1;for(const a of document.querySelectorAll('nav a'))a.setAttribute('aria-current',a.hash===`#${step}`?'page':'false');await ({foundation,onboarding,retrieval,decisions,publisher,accounting,payment,limits}[step])();}
$('#previous').onclick=()=>{const i=steps.indexOf(location.hash.slice(1));location.hash=steps[Math.max(0,i-1)];};$('#next').onclick=()=>{const i=steps.indexOf(location.hash.slice(1));location.hash=steps[Math.min(steps.length-1,i+1)];};window.onhashchange=()=>render().catch(e=>notice(e.message));
try{boot=await request('/v2/bootstrap');catalogue=await request('/v2/evidence');await refresh();await render();}catch(e){notice(e.message);}
