// Presentation only. There is no delivery acknowledgement, signing or model client.
const $=id=>document.getElementById(id);
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const unit=n=>(Number(n)/1e6).toFixed(3);
const sol=n=>(Number(n)/1e9).toFixed(8);
const title=s=>({tripdesk:'TripDesk',agentpass:'AgentPass',hotelops:'HotelOps'}[s]??s);
const tag=s=>`<span class="state">${escape(s)}</span>`;
const number=(n,label)=>`<div class="number"><strong>${escape(n)}</strong><span>${escape(label)}</span></div>`;
const mono=s=>`<span class="mono">${escape(s)}</span>`;
const read=async path=>{const r=await fetch(path);if(!r.ok)throw Error(`Read failed: ${r.status}`);return r.json();};
let run,bootstrap,fixtures=[],index=0;

function campaignScreen(){return `<div class="panel"><table><thead><tr><th>Fictional advertiser</th><th>Declared capability</th><th>Maximum bid</th><th>Spend cap</th><th>Channel</th></tr></thead><tbody>${run.campaigns.map(c=>`<tr><td>${title(c.campaignId)}</td><td>${escape(c.creatives[0].approvedText.replace(/^Fictional [^:]+: /,''))}</td><td>${unit(c.maxBidBaseUnits)}</td><td>${unit(c.budgetCapBaseUnits)}</td><td>${c.campaignId==='tripdesk'?'Funded: 0.020':'Not funded'}</td></tr>`).join('')}</tbody></table><p class="subtle provenance">Amounts are test USDC. All campaigns declare the travel_tools intent; capabilities are advertiser declarations, not verified product performance.</p></div><div class="notice">Only one advertiser was funded. The other advertisers made real skip decisions, but this run does not demonstrate competition between funded bidders.</div>`;}
function evidenceScreen(){return `<div class="thirds">${run.evidence.map(p=>`<section class="panel"><h2>${title(p.campaignId)} profile</h2>${p.observedExamples.map(e=>`<blockquote><strong>${escape(e.advertiser)}</strong><p>${escape(e.text)}</p><span class="subtle">Prompt ${e.promptId} · creative ${e.creativeId} · mapping ${e.mappingId}</span></blockquote>`).join('')}<h3>Inferred context hint</h3><p class="compact">${p.inferredHints.length?p.inferredHints.map(h=>escape(h.text)).join('<br>'):'No inferred hint in this captured profile.'}</p><p class="subtle">${p.inferredHints.length?'Model-inferred targeting, not advertiser configuration.':''} Creative IDs identify observed ads; original creative copy is not in this profile.</p><details><summary>Profile provenance</summary><p>${mono(p.profileHash)}</p><p class="subtle">${escape(p.qualityFlags.join(' · '))}</p></details></section>`).join('')}</div><p class="notice">Actual ContextHint observations informed these profiles. Navan, Auth0 and Software Connect are historical evidence—not enrolled AXP advertisers. Associations are not conversion or task-fit labels.</p>`;}
function decisionScreen(){return `<div class="grid"><section class="panel wide"><table><thead><tr><th>Turn</th><th>Advertiser agent</th><th>Decision</th><th>Fit / 3</th><th>Intent / 3</th><th>Observed ms</th><th>Reason</th></tr></thead><tbody>${run.decisions.map(d=>`<tr><td>${d.turn}</td><td>${title(d.campaignId)}</td><td>${tag(d.decision)}</td><td>${d.relevanceLevel}</td><td>${d.commercialIntentLevel}</td><td>${Math.round(d.attemptElapsedMs)}</td><td>${escape(d.reasonCodes.join(', '))}</td></tr>`).join('')}</tbody></table></section><section class="panel"><h2>Model judges fit; code calculates price</h2><p class="quote">4000 × 7500 / 10000 = 3000 base units</p><p class="subtle">Existing fit_intent_bid_v1 policy: fit 3, intent 2 → 75% of max bid. Deterministic eligibility, floor, budget and funding checks stay outside Jev.</p></section><section class="panel"><h2>Measured, not “low latency”</h2><p>Jev 1.13 returned six valid decisions. These sequential calls took about 1.24–1.51 seconds, including local attempt overhead.</p><p class="subtle">Conversion probability was not estimated. No accuracy or latency advantage over rules is claimed.</p></section></div>`;}
function answersScreen(){return `<p class="notice">User task: ${escape(run.task)}</p><div class="grid">${run.turns.map((t,i)=>`<section class="panel answer"><h2>Organic answer ${i+1}</h2><p class="excerpt">${escape(t.organic.text.slice(0,460))}…</p><details><summary>Read full saved answer</summary><p>${escape(t.organic.text)}</p></details><div class="provenance subtle">${escape(t.organic.provenance.model)} · low reasoning<br>Independent app-agent completion; operator-recorded bridge.<br>No campaign, creative or advertiser profile supplied to this path.</div></section>`).join('')}</div><p class="subtle">The sponsored card is a separate placement, not injected into the organic answer as an undisclosed recommendation.</p>`;}
function deliveryScreen(i){const d=[...run.deliveries].sort((a,b)=>a.charge.sequence-b.charge.sequence)[i],c=d.charge;return `<div class="grid"><section class="sponsor"><strong>Sponsored · fictional advertiser</strong><h2>TripDesk</h2><p class="quote">${escape(d.award.creative.approvedText.replace(/^Fictional [^:]+: /,''))}</p><p>${escape(d.award.creative.destinationURL)}</p><p class="subtle">Reconstructed from the recorded creative. This replay does not render or acknowledge a new paid delivery.</p></section><section class="panel receipt"><h2>Accepted delivery ${i+1}</h2><p>${tag(c.delivery.status)} &nbsp; Charge: ${unit(c.amountBaseUnits)} test USDC</p><dl><dt>Opportunity</dt><dd>${mono(d.award.opportunityId)}</dd><dt>Award</dt><dd>${mono(c.awardId)}</dd><dt>Charge</dt><dd>${mono(c.id)}</dd><dt>Receipt hash</dt><dd>${mono(c.receiptHash)}</dd><dt>Accepted (UTC)</dt><dd>${new Date(c.acceptedAt).toISOString()}</dd></dl><p class="subtle">The original owned-app DOM acknowledgement created the charge. Signed receipt packets were reconstructed on later replay and are marked recordedOnReplay.</p></section></div><p class="notice">Accepted ≠ authorized ≠ settled. Receipt evidence supports disclosed owned-app insertion, not human attention, ad absorption or endorsement.</p>`;}
function voucherScreen(){return `<div class="panel"><table><thead><tr><th>Accepted charge</th><th>Increment</th><th>Cumulative authorization</th><th>Native verification</th></tr></thead><tbody>${run.payment.vouchers.map(v=>`<tr><td>${mono(v.chargeId)}</td><td>${unit(v.incrementBaseUnits)}</td><td>${v.cumulativeAmountBaseUnits} base units · ${unit(v.cumulativeAmountBaseUnits)}</td><td>${tag(v.status)}</td></tr>`).join('')}</tbody></table><p class="subtle provenance">Only voucher hashes and verification receipts are public. Private spending vouchers and signing material are never sent to this console.</p></div><div class="grid"><section class="panel"><h2>One channel, two increments</h2><p class="quote">3000 → 6000</p><p>Deposit, budget reservation, accepted charge and cumulative authorization are distinct states.</p></section><section class="panel"><h2>Trusted worker owns signing</h2><p>The exchange supplies immutable accepted charges. Native MPP sessions verify saved cumulative vouchers; closure uses the final 6000 voucher without adding a new charge.</p></section></div>`;}
function settlementScreen(){const c=run.chain,p=run.payment;return `<div class="numbers">${number(unit(p.depositBaseUnits),'Deposit · test USDC')}${number(unit(p.acceptedBaseUnits),'Accepted charges')}${number(unit(p.authorizedBaseUnits),'Authorized')}${number(unit(p.settledBaseUnits),'Finalized payout')}${number(unit(p.refundBaseUnits),'Unused-deposit refund')}</div><div class="grid"><section class="panel"><h2>Native MPP session · finalized</h2><p>${tag(c.channel.status)} &nbsp; Escrow closed</p><p class="mono">${escape(p.protocolChannelId)}</p><p>One open + one cooperative settlement.</p><p><a href="${escape(c.links.open)}" target="_blank" rel="noreferrer">Sandbox open transaction</a> · <a href="${escape(c.links.settlement)}" target="_blank" rel="noreferrer">Sandbox settlement transaction</a></p><p class="subtle">Saved slots ${p.open.evidence.slot} / ${p.close.evidence.slot}. Explorer is supplementary: the hosted validator can reset. Replay uses saved transaction/account evidence.</p></section><section class="panel"><h2>Fees and rent are separate</h2><table class="compact"><tbody><tr><td>Transaction fees</td><td>${sol(c.networkFeeLamports)} test SOL</td></tr><tr><td>Gross new rent</td><td>${sol(c.grossNewRentLamports)} test SOL</td></tr><tr><td>Escrow rent reclaimed</td><td>${sol(c.reclaimedRentLamports)} test SOL</td></tr><tr><td>Channel rent remains</td><td>${sol(c.channel.remainingRentLamports)} test SOL</td></tr><tr><td>Publisher ATA rent remains</td><td>0.00203928 test SOL</td></tr></tbody></table><p class="subtle">Refund 0.014 is unused test USDC—not rent. No mainnet or Devnet transaction is shown.</p></section></div>`;}
function replayScreen(){const r=run.restart;return `<div class="grid"><section class="panel"><h2>Original fresh-process check</h2><table><thead><tr><th>Recorded counter</th><th>Before</th><th>After</th></tr></thead><tbody><tr><td>Accepted charges</td><td>${r.before.charges.length}</td><td>${r.after.charges.length}</td></tr><tr><td>Model admissions</td><td>${r.before.modelAdmissions}</td><td>${r.after.modelAdmissions}</td></tr><tr><td>Payment record hash</td><td colspan="2">${mono(r.before.paymentRecordHash)}</td></tr></tbody></table><p class="subtle provenance">${escape(r.boundary)}</p></section><section class="panel"><h2>Offline presentation boundary</h2><div class="numbers">${number('0','New model calls')}${number('0','New payment signatures')}${number('0','New broadcasts')}</div><p>Navigation reads a verified bundle. No execution adapters, acknowledgement routes, credentials, wallets or database are available to this process.</p><p class="subtle">These zeros describe this read-only server, not telemetry for other processes on the Mac.</p></section></div><p class="notice">Recorded restart evidence is unchanged. This demonstrates outcome reuse, not a fresh end-to-end paid execution or an injected lost-network-ACK test.</p>`;}
function limitsScreen(){return `<div class="grid"><section class="panel"><h2>Demonstrated</h2><ul><li>Six actual agent bid/skip outputs informed by saved ContextHint profiles.</li><li>Two independent organic answers and two disclosed owned-app deliveries.</li><li>Two accepted charges on one native MPP channel.</li><li>Finalized sandbox payout, unused-funds refund and restart reuse.</li></ul></section><section class="panel"><h2>Not established</h2><ul><li>Ad absorption, attention, endorsement or conversion lift.</li><li>Replication of ChatGPT’s proprietary ad algorithm.</li><li>Competing funded bidders in the recorded run.</li><li>Ultra-low latency or proven targeting improvement.</li><li>Production isolation or public release.</li></ul></section></div><p class="notice">Research outcome: ${escape(run.research.adoption)}. Keep deterministic rules as the default; Jev remains replaceable. AXP’s vision is an advertising exchange for the agentic internet.</p>`;}
function purposeScreen(){return `<p class="lede">Advertiser agents buy disclosed placements in AI applications.</p><div class="flow"><span>Campaign<small>Declared fit and spending caps</small></span><span>Opportunity<small>Agent bid / skip + code rules</small></span><span>Delivery<small>Publisher receipt → charge</small></span><span>MPP channel<small>Cumulative spend → settlement</small></span></div><div class="grid"><section class="panel"><h2>One complete recorded experiment</h2><div class="numbers">${number('6','Jev decisions')}${number('2','Organic answers')}${number('2','Accepted deliveries')}</div><p>Task: ${escape(run.task)}</p></section><section class="panel"><h2>Evidence, not simulated execution</h2><p>The original run used actual models and the official hosted Solana payment sandbox. This console is a self-contained, read-only replay.</p><p class="subtle">The presentation needs no credentials and cannot spend. Synthetic edge cases are separate and clearly labelled.</p></section></div>`;}
const screens={purpose:purposeScreen,campaigns:campaignScreen,evidence:evidenceScreen,decisions:decisionScreen,answers:answersScreen,'delivery-one':()=>deliveryScreen(0),'delivery-two':()=>deliveryScreen(1),vouchers:voucherScreen,settlement:settlementScreen,replay:replayScreen,limits:limitsScreen};
function render(){const s=run.steps[index];$('screen').innerHTML=`<h1>${escape(s.title)}</h1><div class="step-content">${screens[s.id]()}</div>`;$('screen').dataset.step=s.id;$('caption').textContent=s.caption;$('previous').disabled=index===0;$('next').disabled=index===run.steps.length-1;$('step').value=String(index);$('position').textContent=`${index+1} / ${run.steps.length}`;history.replaceState(null,'',`/#${s.id}`);}
function move(delta){index=Math.max(0,Math.min(run.steps.length-1,index+delta));render();}
$('previous').addEventListener('click',()=>move(-1));$('next').addEventListener('click',()=>move(1));$('step').addEventListener('change',()=>{index=Number($('step').value);render();});
document.addEventListener('keydown',e=>{if(['SELECT','INPUT','TEXTAREA'].includes(e.target.tagName)||e.altKey||e.ctrlKey||e.metaKey)return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();move(e.key==='ArrowRight'?1:-1);}if(e.key==='Home'){index=0;render();}if(e.key==='End'){index=run.steps.length-1;render();}});
$('example').addEventListener('change',()=>{const f=fixtures.find(f=>f.id===$('example').value);$('example-content').innerHTML=f?`<strong>${escape(f.sourceKind==='recorded_run'?'Recorded fixture · saved run projection':'Synthetic example · not a sandbox transaction')}</strong><p>${escape(f.description??f.name??f.id)}</p><pre class="mono">${escape(JSON.stringify(f,null,2))}</pre>`:'';});
$('events').addEventListener('click',async()=>{const res=await fetch('/v1/replay/events');$('event-text').textContent=await res.text();});
try{[bootstrap,run]=await Promise.all([read('/v1/replay/bootstrap'),read('/v1/replay/run')]);if(!bootstrap.readOnly||run.presentationKind!=='recorded_evidence_replay'||run.financialMode!=='sandbox')throw Error('Replay boundary mismatch');$('run').textContent=run.runId;$('timestamp').textContent=`Original chain observation ${run.originalRecordedAt}`;$('hash').textContent=`Verified bundle SHA-256: ${bootstrap.bundleHash}`;$('step').innerHTML=run.steps.map((s,i)=>`<option value="${i}">${escape(s.title)}</option>`).join('');const initial=run.steps.findIndex(s=>`#${s.id}`===location.hash);index=initial<0?0:initial;render();try{const data=await read('/v1/replay/fixtures');fixtures=Array.isArray(data)?data:(data.fixtures??[]);$('example').insertAdjacentHTML('beforeend',fixtures.map(f=>`<option value="${escape(f.id)}">${escape(f.id)}</option>`).join(''));}catch{$('example').disabled=true;}}catch(e){$('screen').textContent=`Replay unavailable: ${e.message}`;$('previous').disabled=true;$('next').disabled=true;}
