import {acknowledgePlacement} from '/publisher.mjs';
const $=id=>document.getElementById(id),pretty=v=>JSON.stringify(v,null,2);
let csrf,currentAward=null,busy=false,phase3=null,state=null,financialMode='synthetic';
let randomSessionId=crypto.randomUUID();
async function post(path,data={}){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','x-axp-csrf':csrf},body:JSON.stringify(data)});const v=await r.json();if(!r.ok)throw new Error(v.error);return v;}
function button(text,action){const b=document.createElement('button');b.textContent=text;b.onclick=async()=>{b.disabled=true;try{await action();await refresh();}catch(e){$('status').textContent=e.message;}finally{b.disabled=false;}};return b;}
async function refresh(){const r=await fetch('/v1/state'),s=await r.json();state=s;$('run').textContent=`Run ${s.runId} · ${s.mode}`;$('state').textContent=pretty(s);$('events').textContent=pretty(s.events);$('campaigns').replaceChildren();
  if(s.payments?.length){const p=s.payments[0];$('payment-summary').hidden=false;$('payment-summary').textContent=`${p.phase==='finalized'?'FINALIZED':'Not finalized'} sandbox channel · deposit ${p.depositBaseUnits} · accepted ${p.acceptedBaseUnits} · authorized ${p.authorizedBaseUnits} · settled ${p.settledBaseUnits} · unused refund ${p.refundBaseUnits} test-USDC base units (1 USDC = 1,000,000).`;}
  if(phase3){const n=s.opportunities.length;$('phase-status').textContent=`${phase3.phase}: actual ${phase3.buyerModel} buyers + independent ${phase3.organicModel} (${phase3.organicEffort}) answer. Organic runtime: isolated app-agent completion, operator-recorded bridge; not unattended CLI. ${n}/2 admitted turns. ${financialMode==='synthetic'?'SYNTHETIC accounting.':'Official Solana SANDBOX, not Devnet/mainnet. One funded advertiser; other relevance decisions are checked separately against funding.'}`;$('conversation').querySelector('button').textContent=n>=2?'Replay first placement — no new calls':'Run next actual-model placement';}
  for(const c of s.campaigns){const n=document.createElement('article'),title=document.createElement('strong');title.textContent=`${c.campaignId} · ${c.status}`;n.append(title);const p=document.createElement('p');p.textContent=`${c.destination}; maximum ${c.maxBidBaseUnits} base units; cap ${c.budgetCapBaseUnits}. Fictional declarations.`;n.append(p,button('Pause',()=>post(`/v1/campaigns/${encodeURIComponent(c.campaignId)}/pause`)));$('campaigns').append(n);}
  $('channels').replaceChildren();for(const c of s.channels){const n=document.createElement('article'),p=document.createElement('p');const accepted=s.charges.filter(x=>x.channelId===c.channelId).reduce((sum,x)=>sum+BigInt(x.amountBaseUnits),0n).toString();p.textContent=`${c.channelId} · ${c.status} · deposit ${c.depositBaseUnits} · accepted ${accepted} · authorized ${c.authorizedBaseUnits} · settled ${c.settledBaseUnits} · refund ${c.refundBaseUnits} base units · ${c.mode.toUpperCase()}`;n.append(p);if(c.mode==='synthetic')n.append(button('Synthetic authorize',()=>post(`/v1/synthetic-channels/${c.channelId}/authorize`)),button('Synthetic close',()=>post(`/v1/synthetic-channels/${c.channelId}/close`)));$('channels').append(n);}if(s.payments)$('network-receipts').textContent=pretty(s.payments);}
$('conversation').onsubmit=async event=>{event.preventDefault();if(busy)return;busy=true;const submit=event.currentTarget.querySelector('button');submit.disabled=true;$('status').textContent='Evaluating opportunity…';$('ad').hidden=true;$('fail').hidden=true;currentAward=null;
  try{const turnId=phase3?phase3.turnIds[state.opportunities.length<2?state.opportunities.length:0]:crypto.randomUUID();const result=await post('/v1/demo/turn',{prompt:$('prompt').value,engine:$('engine').value,turnId,randomSessionId});$('organic').textContent=`${result.replayed?'Recorded replay · ':''}${result.organic.source}${result.organic.provenance?.runtime==='isolated-app-agent-operator-bridge'?' · isolated app-agent completion bridge':''}: ${result.organic.text??pretty(result.organic)}`;$('trace').textContent=pretty({engine:result.engine,replayed:result.replayed,originalOrganic:result.originalOrganic??null,organicProvenance:result.organic.provenance??null,eligibility:result.eligibility,attempts:result.attempts,outcome:result.outcome});
    if(result.outcome.award&&['reserved','delivered'].includes(result.outcome.award.status)){currentAward=result.outcome.award;const node=$('ad');node.replaceChildren();node.dataset.awardId=currentAward.id;const label=document.createElement('strong');label.dataset.sponsoredLabel='';label.textContent='Sponsored';const copy=document.createElement('p');copy.dataset.creativeCopy='';copy.textContent=currentAward.creative.approvedText;const link=document.createElement('a');link.href=currentAward.creative.destinationURL;link.textContent='Fictional advertiser website';const note=document.createElement('small');note.textContent='Fictional advertiser declarations; not verified capabilities. An accepted render creates a charge, not a finalized payment.';node.append(label,copy,link,note);node.hidden=false;await new Promise(requestAnimationFrame);const receipt=await acknowledgePlacement({node,award:currentAward,post});$('status').textContent=`${receipt.replayed?'Recorded receipt replay — no new charge.':'Rendered → accepted receipt →'} ${financialMode==='synthetic'?'Synthetic':'Sandbox-bound'} charge ${receipt.charge.amountBaseUnits} base units. Authorization and settlement are separate.`;
    }else $('status').textContent=`${result.outcome.status}: no sponsored placement; no charge.`;await refresh();
  }catch(e){$('status').textContent=e.message;if(currentAward)$('fail').hidden=false;await refresh();}finally{busy=false;submit.disabled=false;}};
$('fail').onclick=async()=>{if(!currentAward)return;try{await post(`/v1/awards/${currentAward.id}/fail`);$('ad').hidden=true;$('fail').hidden=true;await refresh();}catch(e){$('status').textContent=e.message;}};
$('reset').onclick=async()=>{if(busy)return;try{await post('/v1/demo/reset');$('ad').hidden=true;$('organic').textContent='Fresh run. Previous run remains in local storage.';$('trace').textContent='No opportunity yet.';await refresh();}catch(e){$('status').textContent=e.message;}};
$('campaign-form').onsubmit=async e=>{e.preventDefault();try{await post('/v1/campaigns',JSON.parse($('campaign-json').value));await refresh();$('status').textContent='Campaign version saved.';}catch(error){$('status').textContent=error.message;}};
$('evidence-form').onsubmit=async event=>{
  event.preventDefault();const submit=event.currentTarget.querySelector('button');submit.disabled=true;$('evidence-status').textContent='Reading existing cached evidence…';$('evidence-matches').replaceChildren();$('evidence-provenance').textContent='Lookup pending; no result yet.';
  try{
    const r=await post('/v1/evidence/lookup',{prompt:$('evidence-prompt').value});
    $('evidence-status').textContent=r.status==='ready'?`${r.matches.length} historical prompt neighborhoods retrieved. No campaign or payment changed.`:r.status==='query_vector_unavailable'?'This prompt has no cached vector. No embedding was generated; no baseline was disguised as retrieval.':'Local corpus adapter is not configured.';
    $('evidence-provenance').textContent=pretty({provenance:r.provenance??null,limitations:r.limitations});
    for(const m of r.matches){const n=document.createElement('article'),title=document.createElement('strong');title.textContent=`Observed prompt: ${m.promptText}`;const score=document.createElement('p');score.textContent=`Cached-vector cosine ${m.similarity.toFixed(3)} — similarity, not conversion probability.`;n.append(title,score);
      for(const a of m.mappings){const creative=document.createElement('p');creative.textContent=`Historical ${a.advertiser}: ${a.creativeText}`;n.append(creative);if(a.hint){const h=document.createElement('p');h.textContent=`Inferred targeting (${a.hint.tier}; ${a.hint.modelVersion}): ${a.hint.text}`;n.append(h);}}
      $('evidence-matches').append(n);
    }
  }catch(e){$('evidence-status').textContent=e.message;}finally{submit.disabled=false;}
};
const bootstrap=await (await fetch('/v1/bootstrap')).json();csrf=bootstrap.csrf;
financialMode=bootstrap.mode;
if(financialMode!=='synthetic'){$('financial-label').textContent='Official Solana payment SANDBOX · not Devnet or mainnet';$('payment-boundary').textContent='Deposit, reservation, accepted charge, native cumulative voucher, finalized settlement and refund are separate. Signing requires the operator terminal; no browser payment buttons.';$('research-boundary').textContent='Phase 4 connects six actual Jev decisions, two independently generated app-agent answers, two disclosed owned-app deliveries and native MPP cumulative vouchers to one finalized sandbox settlement. Only one advertiser has a funded channel; this is not a multiple-funded-bidder auction demonstration. Phase 2 historical comparisons remain separate and show no proven targeting or latency advantage. Organic answers use an operator-recorded bridge, not unattended CLI. A receipt asserts DOM insertion and disclosure, not attention, context absorption, endorsement or conversions.';}
if(bootstrap.demo){phase3=bootstrap.demo;randomSessionId=phase3.randomSessionId;$('prompt').value=phase3.task;$('prompt').readOnly=true;$('engine').replaceChildren();for(const engine of bootstrap.engines){const option=document.createElement('option');option.value=engine.id;option.textContent=engine.label;$('engine').append(option);}$('reset').disabled=true;$('campaign-form').querySelector('button').disabled=true;}
const decisionCases=await (await fetch('/v1/decisions/cases')).json();
for(const task of decisionCases.cases){const option=document.createElement('option');option.value=task.id;option.textContent=task.prompt;$('decision-case').append(option);}
const recorded=await(await fetch('/v1/decisions/recorded')).json();
$('recorded-status').textContent=`${recorded.totalProviderUsage.calls} actual calls recorded; initial 24 produced no valid decisions. Three corrected probes produced bid/skip at 512–529ms. Rules remain the default; no demonstrated targeting lift.`;
$('recorded-summary').textContent=pretty(recorded);
for(const d of recorded.diagnosticCorrection.successfulDecisions){const node=document.createElement('article'),title=document.createElement('strong'),p=document.createElement('p');title.textContent=`Recorded ${recorded.model}: ${d.campaignId} → ${d.decision}`;p.textContent=`${d.caseId}; declared fit ${d.relevanceLevel}/3; intent ${d.commercialIntentLevel}/3; ${d.engineElapsedMs.toFixed(1)}ms. Evidence replay only — no fresh model call, auction or charge.`;node.append(title,p);$('recorded-decisions').append(node);}
$('decision-form').onsubmit=async event=>{
  event.preventDefault();const submit=event.currentTarget.querySelector('button');submit.disabled=true;$('decision-status').textContent='Evaluating frozen task…';$('decision-results').replaceChildren();$('decision-evidence').textContent='Pending.';
  try{
    const r=await post('/v1/decisions/compare',{caseId:$('decision-case').value});
    $('decision-status').textContent=`${r.attempts.length} own-campaign decisions. ${r.preparationError??'Existing evidence profiles prepared.'} No placement or charge. Jev live trials are separate bounded CLI runs.`;
    $('decision-evidence').textContent=pretty(r);
    for(const a of r.attempts){const node=document.createElement('article'),title=document.createElement('strong'),p=document.createElement('p');title.textContent=`${a.campaignId} · ${a.decision.engineProvenance.engine} → ${a.decision.decision}`;p.textContent=`Relevance ${a.decision.relevanceLevel??'unavailable'}; intent ${a.decision.commercialIntentLevel??'unavailable'}; ${a.decision.engineProvenance.elapsedMs.toFixed(1)}ms. ${a.decision.reasonCodes.join(', ')}. ${a.decision.engineProvenance.failureReason??''}`;node.append(title,p);$('decision-results').append(node);}
  }catch(e){$('decision-status').textContent=e.message;}finally{submit.disabled=false;}
};
$('evidence-source').textContent=bootstrap.evidenceSource?.enabled?'Read-only local ads corpus enabled. Database embeddings reused; artifact revision unrecorded.':'Not enabled. Launch with AXP_CORPUS_DB=ads to use the existing local database.';
await refresh();
