import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {once} from 'node:events';
import {createAdvertiserSimulation,simulationOpportunity,PRESETS} from '../../packages/advertiser/service.mjs';
import {createAdvertiserServer} from '../../apps/backend/advertiser.mjs';
import {hash} from '../../packages/contracts/index.mjs';
import {createAdvertiserClient} from '../../packages/advertiser/client.mjs';

function catalogue(){const c={schemaVersion:'advertiser-evidence.v1',capturedAt:'2026-10-01T00:00:00.000Z',sourceMode:'cached_database_export',inventory:{schemaVersion:'cached-corpus-inventory.v1',provenance:{database:'ads',readOnly:true,model:'BAAI/bge-base-en-v1.5',dimension:768,revision:'unrecorded',category:'travel-hospitality',embeddingCalls:0},vectors:{prompt:1,ad:1,hint:0},travel:{backgroundProbes:1,backgroundMappings:1,backgroundCreatives:1,hints:0,hintVectors:0}},limitations:['Synthetic test evidence, not the demo export'],records:[{id:'ads:mapping:3',promptId:1,promptText:'Corporate travel booking',creativeId:2,mappingId:3,advertiser:'Historical fixture',creativeText:'Observed fixture copy',hint:null,source:{database:'ads',readOnly:true,sourceHash:'a'.repeat(64),category:'travel-hospitality',revision:'unrecorded',selectionVersion:'advertiser-travel-bounded-v1',creativeTextStatus:'historical_observed_copy',queryTextHashes:['b'.repeat(64)]}}]};return {...c,contentHash:hash(c)};}
function draft(p=PRESETS[0],overrides={}){return {...p,contextHints:p.contextHints,declaredCapabilities:p.declaredCapabilities,evidenceIds:['ads:mapping:3'],maxBidBaseUnits:'4000',budgetCapBaseUnits:'8000',depositBaseUnits:'20000',approved:true,...overrides,...{id:undefined}};}
function input(p,overrides){const {id,...d}=draft(p,overrides);return d;}
function setup(){const dir=mkdtempSync(join(tmpdir(),'axp-advertiser-test-'));const sim=createAdvertiserSimulation({stateDir:dir,catalogue:catalogue()});const finish=()=>{sim.close();rmSync(dir,{recursive:true,force:true});};return {dir,sim,finish};}
function account(sim){return sim.saveAccount({accountName:'Fictional account',brandName:'TripDesk',websiteURL:'https://tripdesk.example/'});}
function launch(sim,p=PRESETS[0],overrides={}){account(sim);const d=sim.saveDraft(input(p,overrides));return sim.launchCampaign(d.draftId).campaign;}
function turn(turnId='turn-1',prompt='Compare tools for corporate travel booking and automatic expense capture.'){return {prompt,turnId,randomSessionId:'session-1'};}
function render(sim,result){const a=result.outcome.award;return sim.acknowledge(a.id,{domInserted:true,sponsoredLabelPresent:true,creativeHash:a.creativeHash});}

test('frontend extension client follows implemented simulation routes and never offers wallet access',async()=>{
  assert.throws(()=>createAdvertiserClient({baseURL:'https://example.com'}),/loopback/);
  const dir=mkdtempSync(join(tmpdir(),'axp-advertiser-client-')),server=createAdvertiserServer({stateDir:dir,catalogue:catalogue()});
  server.listen(0,'127.0.0.1');await once(server,'listening');
  const client=createAdvertiserClient({baseURL:`http://127.0.0.1:${server.address().port}`});
  try{
    await assert.rejects(()=>client.saveAccount({}),/bootstrap_required/);
    assert.equal((await client.bootstrap()).presentation,'fresh_deterministic_simulation');
    assert.equal((await client.evidence('travel')).records.length,1);
    await client.saveAccount({accountName:'Demo',brandName:'TripDesk',websiteURL:'https://tripdesk.example/'});
    const d=await client.saveDraft(input()),c=(await client.launch(d.draftId)).campaign;
    assert.equal((await client.preview({draftId:d.draftId,prompt:turn().prompt})).previewOnly,true);
    const before=hash(await client.state());
    const comparison=await client.compare({campaignId:c.campaignId,prompt:turn().prompt});
    assert.equal(comparison.previewOnly,true);assert.equal(comparison.fundingEligibility.eligible,true);assert.equal(hash(await client.state()),before);
    const live=await client.turn(turn());
    assert.deepEqual(live.attempts[0].decision.engineProvenance,comparison.history.decision.engineProvenance);
    const a=live.outcome.award;
    assert.equal((await client.acknowledgeRender(a.id,{domInserted:true,sponsoredLabelPresent:true,creativeHash:a.creativeHash})).charge.amountBaseUnits,'3000');
    assert.equal((await client.authorize(c.channelId)).authorizedBaseUnits,'3000');
    assert.equal((await client.close(c.channelId)).refundBaseUnits,'17000');
    assert.equal((await client.state()).charges.length,1);
    const closed=await client.compare({campaignId:c.campaignId,prompt:turn().prompt});
    assert.equal(closed.fundingEligibility.reason,'channel_not_open');assert.equal(closed.history.bid.status,'no_bid');
    assert.equal(client.openWallet,undefined);
    assert.throws(()=>client.launch('../payment'),/invalid_id/);
  }finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));rmSync(dir,{recursive:true,force:true});}
});

test('onboarding, evidence IDs, creative approval and simulation ceilings are enforced',()=>{const {sim,finish}=setup();try{
  const d=sim.saveDraft(input(PRESETS[0],{approved:false}));assert.throws(()=>sim.launchCampaign(d.draftId),{code:'complete_onboarding'});account(sim);assert.throws(()=>sim.launchCampaign(d.draftId),{code:'creative_not_approved'});
  assert.throws(()=>sim.saveDraft(input(PRESETS[0],{evidenceIds:['invented']})),{code:'unknown_evidence'});assert.throws(()=>sim.saveDraft(input(PRESETS[0],{depositBaseUnits:'100'})),{code:'invalid_demo_budget'});assert.throws(()=>sim.saveDraft({...input(),walletKey:'secret'}),{code:'unknown_field'});
  assert.equal(sim.state().mode,'synthetic');assert.equal(sim.state().account.identityVerification,'not_performed_demo_only');
}finally{finish();}});
test('preview uses prepared evidence but creates no opportunities, reservations or charges',()=>{const {sim,finish}=setup();try{const d=sim.saveDraft(input());const before=hash(sim.state());const r=sim.preview({draftId:d.draftId,prompt:turn().prompt});assert.equal(r.decision.decision,'bid');assert.equal(r.bid.amountBaseUnits,'3000');assert.equal(r.previewOnly,true);assert.deepEqual(r.decision.engineProvenance.supportingHistoricalEvidenceIds,[]);assert.equal(r.decision.engineProvenance.fallbackReason,'no_aligned_historical_support');assert.equal(r.selectedEvidence[0].id,'ads:mapping:3');assert.equal(hash(sim.state()),before);}finally{finish();}});
test('launch replay and immutable drafts survive restart',()=>{const {dir,sim}=setup();let restarted;try{account(sim);const d=sim.saveDraft(input());const a=sim.launchCampaign(d.draftId);assert.equal(sim.launchCampaign(d.draftId).replayed,true);assert.throws(()=>sim.saveDraft({...input(),draftId:d.draftId}),{code:'launched_draft_immutable'});sim.close();restarted=createAdvertiserSimulation({stateDir:dir,catalogue:catalogue()});assert.equal(restarted.state().campaigns.length,1);assert.equal(restarted.launchCampaign(d.draftId).campaign.campaignId,a.campaign.campaignId);assert.equal(restarted.state().channels.length,1);}finally{restarted?.close();rmSync(dir,{recursive:true,force:true});}});
test('three simulated buyers show one bid, genuine deterministic skips and isolated organic task fields',async()=>{const {sim,finish}=setup();try{PRESETS.forEach(p=>launch(sim,p));const result=await sim.turn(turn());assert.equal(result.attempts.filter(a=>a.decision.decision==='bid').length,1);assert.equal(result.attempts.filter(a=>a.decision.decision==='skip').length,2);assert.equal(result.organic.source,'deterministic-reference-not-llm');assert.equal(result.organic.advertiserMaterialIncluded,false);assert.ok(!JSON.stringify(result.organic.inputProjection).includes('TripDesk'));assert.ok(result.attempts.every(a=>a.decision.engineProvenance.model===null));const receipt=render(sim,result);assert.equal(receipt.charge.amountBaseUnits,'3000');assert.equal(sim.state().charges.length,1);assert.equal(sim.state().summaries.filter(s=>s.acceptedBaseUnits==='0').length,2);}finally{finish();}});
test('two deliveries accumulate once, same-turn retries do not pay, and synthetic close refunds unused deposit',async()=>{const {sim,finish}=setup();try{const c=launch(sim);const r1=await sim.turn(turn());render(sim,r1);const replay=await sim.turn(turn());assert.equal(replay.replayed,true);assert.equal(render(sim,replay).replayed,true);const r2=await sim.turn(turn('turn-2'));render(sim,r2);assert.equal(sim.authorize(c.channelId).authorizedBaseUnits,'6000');assert.equal(sim.authorize(c.channelId).authorizedBaseUnits,'6000');const close=sim.settle(c.channelId);assert.equal(close.settledBaseUnits,'6000');assert.equal(close.refundBaseUnits,'14000');assert.equal(close.txSignature,null);assert.equal(sim.settle(c.channelId).settledBaseUnits,'6000');assert.equal(sim.state().charges.length,2);assert.throws(()=>sim.campaignStatus({campaignId:c.campaignId,status:'active'}),{code:'channel_closed'});}finally{finish();}});
test('failed delivery, no-fill, paused and required-capability mismatches produce zero charge',async()=>{const {sim,finish}=setup();try{const c=launch(sim);const r=await sim.turn(turn());sim.failAward(r.outcome.award.id);assert.throws(()=>render(sim,r),{code:'award_expired'});assert.equal((await sim.turn(turn('education','Explain corporate travel booking.'))).outcome.status,'no_fill');assert.equal((await sim.turn(turn('identity','I need authentication for AI travel agents.'))).outcome.status,'no_fill');sim.campaignStatus({campaignId:c.campaignId,status:'paused'});assert.equal((await sim.turn(turn('paused'))).outcome.status,'no_fill');assert.equal(sim.state().charges.length,0);assert.equal(sim.state().summaries[0].reservedBaseUnits,'0');}finally{finish();}});
test('competing simulated bids use actual integer first-price auction, losers cost zero',async()=>{const {sim,finish}=setup();try{const a=launch(sim);const b=launch(sim,PRESETS[0],{brandName:'Other fictional travel tool',name:'Second bidder',maxBidBaseUnits:'5000',budgetCapBaseUnits:'10000'});const result=await sim.turn(turn());assert.equal(result.outcome.bids.length,2);assert.equal(result.outcome.award.campaignId,b.campaignId);assert.equal(result.outcome.award.priceBaseUnits,'3750');render(sim,result);assert.equal(sim.state().summaries.find(x=>x.campaignId===a.campaignId).acceptedBaseUnits,'0');}finally{finish();}});
test('cap, disclosure, conflicting turn and restart receipt outcomes are guarded',async()=>{const {dir,sim}=setup();let restarted;try{launch(sim,PRESETS[0],{budgetCapBaseUnits:'4000'});const r=await sim.turn(turn());assert.throws(()=>sim.acknowledge(r.outcome.award.id,{domInserted:true,sponsoredLabelPresent:false,creativeHash:r.outcome.award.creativeHash}),{code:'render_ack_invalid'});render(sim,r);await assert.rejects(()=>sim.turn({...turn(),prompt:'Changed prompt'}),{code:'idempotency_conflict'});const r2=await sim.turn(turn('turn-2'));assert.equal(r2.outcome.award.priceBaseUnits,'1000');render(sim,r2);assert.equal(sim.state().summaries[0].acceptedBaseUnits,'4000');assert.equal((await sim.turn(turn('turn-3'))).outcome.status,'no_fill');sim.close();restarted=createAdvertiserSimulation({stateDir:dir,catalogue:catalogue()});const replay=await restarted.turn(turn());assert.equal(replay.replayed,true);assert.equal(render(restarted,replay).replayed,true);assert.equal(restarted.state().charges.length,2);
}finally{restarted?.close();rmSync(dir,{recursive:true,force:true});}});
test('HTTP wizard to simulated delivery and close has no network/payment/model endpoints',async()=>{const dir=mkdtempSync(join(tmpdir(),'axp-advertiser-http-'));const server=createAdvertiserServer({stateDir:dir,catalogue:catalogue()});server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;try{const b=await (await fetch(origin+'/v1/advertiser/bootstrap')).json();const post=async(path,data={})=>{const response=await fetch(origin+path,{method:'POST',headers:{'Content-Type':'application/json','x-axp-csrf':b.csrf},body:JSON.stringify(data)});return {status:response.status,data:await response.json()};};assert.equal(b.mode,'synthetic');assert.equal((await post('/v1/advertiser/account',{accountName:'Demo',brandName:'TripDesk',websiteURL:'https://tripdesk.example/'})).status,200);const d=await post('/v1/advertiser/drafts',input());const c=await post(`/v1/advertiser/drafts/${d.data.draftId}/launch`);const r=await post('/v1/advertiser/turn',turn());const a=r.data.outcome.award;assert.equal((await post(`/v1/awards/${a.id}/render`,{domInserted:true,sponsoredLabelPresent:true,creativeHash:a.creativeHash})).status,200);assert.equal((await post(`/v1/advertiser/channels/${c.data.campaign.channelId}/authorize`)).data.authorizedBaseUnits,'3000');const settled=await post(`/v1/advertiser/channels/${c.data.campaign.channelId}/close`);assert.equal(settled.data.refundBaseUnits,'17000');assert.equal((await post('/v1/payment-sessions/open-approved')).status,404);assert.equal((await fetch(origin+'/v1/advertiser/account',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,403);assert.equal((await fetch(origin+'/')).status,200);assert.equal((await fetch(origin+'/design-system/fonts/PolySans-Neutral.woff2')).status,200);}finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));rmSync(dir,{recursive:true,force:true});}});
