import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createSession} from '../../apps/backend/session.mjs';
import {createDemoServer} from '../../apps/backend/server.mjs';
import {campaignFixtures} from '../../packages/contracts/fixtures.mjs';
import {makeDecisionRequest,validateEngineForExchange} from '../../packages/dsp/decision-engine.mjs';
import {RuleDecisionEngine} from '../../packages/ml/index.mjs';

const prompt='Find a hotel near Marina Bay in Singapore; solo traveller, free cancellation.';
const ack=a=>({domInserted:true,sponsoredLabelPresent:true,creativeHash:a.creativeHash});
function setup(t,options={}){const dir=mkdtempSync(join(tmpdir(),'axp-connected-'));const session=createSession({stateDir:dir,...options});t.after(()=>{session.close();rmSync(dir,{recursive:true,force:true});});return {session,dir};}
test('connected baseline: task, auction, signed acknowledgement, two cumulative charges and replay',async t=>{
  const {session}=setup(t);const first=await session.turn({prompt,turnId:'one',engine:'ml-rules'});assert.equal(first.outcome.award.campaignId,'baystay');assert.equal(first.organic.source,'deterministic-reference');assert.equal(first.attempts.length,2);assert.ok(first.outcome.rejections.some(x=>x.campaignId==='alpinestay'));assert.equal(first.attempts[0].decision.engineProvenance.engine,'rules_v1');
  const a=first.outcome.award;assert.ok(!('renderTokenHash' in a));const receipt=session.acknowledge(a.id,ack(a));assert.equal(receipt.charge.amountBaseUnits,'4000');assert.equal(session.acknowledge(a.id,ack(a)).replayed,true);
  const repeat=await session.turn({prompt,turnId:'one',engine:'ml-rules'});assert.equal(repeat.replayed,true);assert.equal(repeat.outcome.award.id,a.id);
  session.exchange.authorizeSynthetic(a.channelId);const second=await session.turn({prompt,turnId:'two',engine:'ml-rules'});session.acknowledge(second.outcome.award.id,ack(second.outcome.award));assert.equal(session.exchange.authorizeSynthetic(a.channelId).authorizedBaseUnits,'8000');const close=session.exchange.closeSynthetic(a.channelId);assert.equal(close.refundBaseUnits,'12000');assert.equal(close.txSignature,null);assert.deepEqual(session.exchange.closeSynthetic(a.channelId),close);assert.equal(session.exchange.totals({campaignId:'marinarooms'}).accepted,0n);
});
test('rules skip is labelled deterministic, not a genuine model skip',async t=>{const {session}=setup(t);const c=campaignFixtures()[0];session.exchange.createCampaign({...c,campaignVersionId:'baystay-group',creatives:[{...c.creatives[0],creativeVersionId:'group-v1',approvedText:'Singapore hotel stays for conference groups and teams.',softFitTags:['group']}]});const r=await session.turn({prompt,engine:'ml-rules',turnId:'skip'});const d=r.attempts.find(x=>x.campaignId==='baystay').decision;assert.equal(d.decision,'skip');assert.equal(d.engineProvenance.model,null);});
test('no-fill and failed rendering create no charges',async t=>{const {session}=setup(t);const nofill=await session.turn({prompt:'Explain hotel cancellation policies in Singapore',turnId:'info'});assert.equal(nofill.outcome.status,'no_fill');assert.equal(nofill.organic.status,'completed');const r=await session.turn({prompt,turnId:'fail'}),a=r.outcome.award;assert.throws(()=>session.acknowledge(a.id,{...ack(a),sponsoredLabelPresent:false}),{code:'render_ack_invalid'});session.exchange.failAward(a.id);assert.throws(()=>session.acknowledge(a.id,ack(a)),{code:'award_expired'});assert.equal(session.exchange.report().charges.length,0);});
test('restart recovers same turn and receipt without second model or charge',async t=>{const dir=mkdtempSync(join(tmpdir(),'axp-restart-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));let s=createSession({stateDir:dir});const r=await s.turn({prompt,turnId:'same'}),a=r.outcome.award;s.acknowledge(a.id,ack(a));s.close();s=createSession({stateDir:dir});try{const replay=await s.turn({prompt,turnId:'same'});assert.equal(replay.replayed,true);assert.equal(replay.outcome.award.status,'delivered');assert.equal(s.acknowledge(a.id,ack(a)).replayed,true);assert.equal(s.exchange.report().charges.length,1);await assert.rejects(()=>s.turn({prompt:'Different Singapore hotel',turnId:'same'}),{code:'idempotency_conflict'});}finally{s.close();}});
test('expired reservations are released before next bidder eligibility',async t=>{let now=100000;const {session}=setup(t,{now:()=>now});session.exchange.pauseCampaign('marinarooms');await session.turn({prompt,turnId:'reserved1'});await session.turn({prompt,turnId:'reserved2'});now+=180001;const next=await session.turn({prompt,turnId:'after-expiry'});assert.equal(next.outcome.status,'awarded');assert.equal(session.exchange.report().awards.filter(a=>a.status==='expired').length,2);assert.equal(session.exchange.totals({campaignId:'baystay'}).reserved,4000n);});
test('failed award replay reports current ledger state and does not re-auction',async t=>{const {session}=setup(t);const r=await session.turn({prompt,turnId:'failed-replay'});session.exchange.failAward(r.outcome.award.id);const again=await session.turn({prompt,turnId:'failed-replay'});assert.equal(again.outcome.award.status,'failed');assert.equal(again.replayed,true);assert.equal(session.exchange.report().awards.length,1);});
test('organic-answer input is sanitized and excludes sponsor campaign',async t=>{const {session}=setup(t);let captured;await session.turn({prompt:'Find Singapore hotel, free cancellation; email me at private@example.com',turnId:'privacy'},{answer:async input=>{captured=JSON.stringify(input);return {status:'completed',source:'injected-test',text:'test-only'};}});assert.ok(!captured.includes('private@example'));assert.ok(!captured.includes('baystay'));assert.ok(!captured.includes('approvedText'));});
test('decision seam omits financial and competitor authority',async t=>{const {session}=setup(t);const o=session.exchange.createOpportunity({...await (async()=>{const {sanitizedOpportunity}=await import('../../packages/dsp/rules.mjs');return sanitizedOpportunity(prompt,{turnId:'seam'});})()},{idempotencyKey:'seam'}),c=campaignFixtures()[0];const request=makeDecisionRequest(c,o,{runId:session.exchange.runId});const text=JSON.stringify(request);assert.ok(!text.includes('maxBidBaseUnits'));assert.ok(!text.includes('channelId'));assert.ok(!text.includes('marinarooms'));const d=await new RuleDecisionEngine().scoreOpportunity(request);assert.equal(validateEngineForExchange(d,c,o,request).decision,'bid');});
test('HTTP connected flow, strict fields, operator boundary and fresh-run preservation',async t=>{
  const dir=mkdtempSync(join(tmpdir(),'axp-http-')),server=createDemoServer({stateDir:dir});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});const origin=`http://127.0.0.1:${server.address().port}`;
  const bootstrap=await (await fetch(origin+'/v1/bootstrap')).json();const post=async(path,data={},headers={})=>fetch(origin+path,{method:'POST',headers:{'Content-Type':'application/json','x-axp-csrf':bootstrap.csrf,...headers},body:JSON.stringify(data)});
  assert.equal((await post('/v1/demo/turn',{prompt},{'x-axp-csrf':'wrong'})).status,403);assert.equal((await post('/v1/demo/turn',{prompt},{Origin:'https://external.example'})).status,403);assert.equal((await post('/v1/demo/turn',{prompt,pay:true})).status,400);
  const response=await post('/v1/demo/turn',{prompt,turnId:'http'});assert.equal(response.status,200);const result=await response.json(),a=result.outcome.award;assert.equal((await post(`/v1/awards/${a.id}/render`,ack(a))).status,200);const state=await (await fetch(origin+'/v1/state')).json();assert.equal(state.charges.length,1);assert.ok(!JSON.stringify(state).includes('PRIVATE KEY'));assert.ok(!JSON.stringify(state).includes('renderTokenHash'));
  const reset=await (await post('/v1/demo/reset')).json();assert.equal(reset.historyPreserved,true);assert.notEqual(reset.runId,state.runId);assert.equal((await (await fetch(origin+'/v1/state')).json()).charges.length,0);assert.ok(server.getSession().exchange.db.prepare('SELECT count(*) AS n FROM charges').get().n===1);assert.ok(readFileSync(join(dir,'publisher-receipt.pem'),'utf8').includes('PRIVATE KEY'));
});
