/** Backend-issued DTOs. This client owns no policy, ledger or signing keys. */
export type FinancialMode='synthetic';
export type Presentation='interactive-reference'|'recorded-replay';
export type RetrievalMethod='vector'|'lexical_fallback'|'unavailable';
export type BaseUnits=string;
export interface ObservedExample {id:string;text:string;mappingId:number;promptId:number;creativeId:number;normalizedHash:string;similarity:number;hintIds:string[];source:Record<string,unknown>}
export interface InferredHint {id:string;text:string;tier:string;qualityFlags:string[];sourceHintId?:number;supportingCreativeIds?:number[]}
export interface Profile {schemaVersion:'retrieved-campaign-profile.v1';profileId:string;profileHash:string;campaignId:string;campaignVersionId:string;campaignContentHash:string;snapshotId:string;snapshotContentHash:string;retrievalMethod:RetrievalMethod;historyStatus:'ready'|'unavailable';observedExamples:{id:string;text:string}[];inferredHints:InferredHint[];contrastExamples:{id:string;text:string}[]}
export interface Retrieval {method:RetrievalMethod;fallback:boolean;sourceHash:string;examples:ObservedExample[];hints:InferredHint[];profile:Profile|null;historyStatus:'ready'|'unavailable';queryTextHash:string;queryVectorId:number|null;qualityFlags:string[];neighborCount:number;independentPromptCount:number}
export interface Creative {creativeVersionId:string;approvedText:string;destinationURL:string;fictional:true;softFitTags:string[];evidenceFieldIds:string[]}
export interface Campaign {campaignId:string;campaignVersionId:string;advertiserId:string;status:'active';allowedIntents:string[];destination:string;declaredConstraints:string[];creatives:Creative[];softFitTags:string[];maxBidBaseUnits:BaseUnits;budgetCapBaseUnits:BaseUnits;channelId:string;policyVersion:string}
export interface CampaignDraft {campaignId:string;businessName:string;creative:string;contextHints:string;approved:boolean}
export interface SavedDraft {campaign:Campaign;businessName:string;contextHints:string;approved:boolean;fictional:true;name:string}
export interface Usage {inputTokens:number;outputTokens:number}
export interface Decision {schemaVersion:'agent-decision.v1';opportunityId:string;advertiserId:string;campaignVersionId:string;agentRunId:string;decision:'bid'|'skip'|'abstain';creativeVersionId:string|null;relevanceLevel:number|null;commercialIntentLevel:number|null;conversionProbability:null;reasonCodes:string[];evidenceFieldIds:string[];engineProvenance:{engine:string;model:string;transportMode:'live'|'fixture';profileHash:string|null;snapshotHash:string|null;elapsedMs:number;outcome:string;failureReason:string|null;usage:Usage|null}}
export interface PairedCall {callId:string;questionIndex:number;task:string;campaignId:string;campaignVersionId:string;arm:'text_only'|'history';status:'completed'|'failed'|'unavailable'|'uncertain'|'admitted';admittedAt:number|null;completedAt:number|null;elapsedMs:number;decision:Decision;retrieval:Retrieval|null;requestHash:string;rawOutput:Record<string,unknown>|null;usage:Usage|null;failure:{code:string;stage:string}|null}
export interface ModelAllowance {runId:string;plannedCalls:number;admittedCalls:number;completedCalls:number;unavailableCalls:number;failedCalls:number;uncertainCalls:number;pendingCalls:number;remainingCalls:number;maxCalls:number;inputHash:string|null;freezeHash:string|null;usage:Usage&{unknownUsageCalls:number}}
export interface Bid {id:string;opportunityId:string;campaignId:string;campaignVersionId:string;creativeVersionId:string;agentRunId:string;amountBaseUnits:BaseUnits;bidPolicyVersion:string;status:'bid'}
export interface Award {id:string;runId:string;mode:FinancialMode;opportunityId:string;publisherId:string;campaignId:string;campaignVersionId:string;channelId:string;creativeVersionId:string;creativeHash:string;creative:Creative;winningBidId:string;priceBaseUnits:BaseUnits;status:'reserved'|'delivered'|'failed'|'expired';createdAt:number;expiresAt:number}
export interface Charge {id:string;runId:string;mode:FinancialMode;awardId:string;campaignId:string;campaignVersionId:string;channelId:string;amountBaseUnits:BaseUnits;receiptHash:string;deliveryId:string;sequence:number;status:'accepted'|'authorized'|'settled';acceptedAt:number}
export interface Channel {channelId:string;advertiserId:string;mode:FinancialMode;depositBaseUnits:BaseUnits;authorizedBaseUnits:BaseUnits;settledBaseUnits:BaseUnits;refundBaseUnits:BaseUnits;txSignature:null;status:string}
export interface Turn {questionIndex:number;task:string;opportunityId:string;organic:{source:'sponsor-free-deterministic-reference';text:string;advertiserMaterialReceived:false};records:PairedCall[];policyExclusions:{campaignId:string;reason:string;originalDecision:string}[];outcome:{status:'awarded'|'no_fill';award?:Award;bids:Bid[];rejections:{campaignId:string;reason:string}[]}}
export interface Manifest {schemaVersion:'v2-evidence-manifest.v1';snapshotId:string;contentHash:string;capturedAt:string;counts:{associations:number;normalizedPrompts:number;creatives:number;hints:number;vectors:number;queryVectors:number};source:{readOnly:true;embeddingCalls:0};limitations:string[]}
export interface Acknowledgement {domInserted:true;sponsoredLabelPresent:true;creativeHash:string}
export interface V2State {schemaVersion:'axp.v2-state.v1';runId:string;financialMode:FinancialMode;presentation:Presentation;bundleHash?:string;modelEnabled:boolean;running:boolean;model:ModelAllowance;drafts:SavedDraft[];freeze:null|{at:number;contentHash:string;questions:string[];campaigns:Campaign[];manifest:Manifest};completed:null|{at:number;execution:'actual-jev'|'fixture';financialMode:FinancialMode;paired:PairedCall[];turns:Turn[]};exchange:{campaigns:Campaign[];awards:Award[];charges:Charge[];channels:Channel[];events:{seq:number;type:string;at:number;data:Record<string,unknown>}[]};limitations:string[]}
export interface DeliveryResult {replayed?:boolean;charge:Charge;delivery:{id:string;status:'accepted';receiptHash:string;receivedAt:number}}
export interface HistoricalRecord {id:string;mappingId:number;promptId:number;promptText:string;creativeId:number;creativeText:string;advertiser:string;normalizedHash:string;hintIds:string[];source:Record<string,unknown>}
export interface Catalogue {schemaVersion:string;contentHash:string;records:HistoricalRecord[];hints:InferredHint[]}
export interface Bootstrap {csrf:string|null;replay:boolean;questions:string[];names:Record<string,string>;manifest:Manifest}
/** V1 has a separate identity/network. Never merge its settlement into V2. */
export interface V1PaymentEvidence {runId:string;mode:'sandbox';network:string;cumulativeBaseUnits:BaseUnits;publisherPayoutBaseUnits:BaseUnits;payerRefundBaseUnits:BaseUnits;links:Record<string,unknown>;originalRunId?:string;originalFinancialMode?:'sandbox';presentation?:'separate-recorded-example';bundleHash?:string;payment?:Record<string,unknown>}
export interface V2Client {bootstrap():Promise<Bootstrap>;state():Promise<V2State>;evidence():Promise<Catalogue>;retrieval(question:0|1,campaign:string):Promise<Retrieval>;v1Payment():Promise<V1PaymentEvidence>;saveCampaign(d:CampaignDraft):Promise<SavedDraft>;preview():Promise<Record<string,unknown>>;run():Promise<V2State>;closeAccounting():Promise<V2State>;acknowledge(awardId:string,ack:Acknowledgement):Promise<DeliveryResult>;failDelivery(awardId:string):Promise<Record<string,unknown>>}
export function createV2Client(options?:{baseURL?:string;fetchImpl?:typeof fetch}):V2Client;
