import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createV3Server} from '../../apps/backend/v3.mjs';
import {createClient} from '../../packages/v3/client.mjs';
import {loadEvidence} from '../../packages/v2/evidence.mjs';

async function server(t){const directory=mkdtempSync(join(tmpdir(),'v3-http-'));const app=createV3Server({stateDir:directory,payee:'fixture-publisher',retriever:loadEvidence()});await new Promise((r,j)=>{app.once('error',j);app.listen(0,'127.0.0.1',r);});const baseURL=`http://127.0.0.1:${app.address().port}`;t.after(async()=>{await new Promise(r=>app.close(r));rmSync(directory,{recursive:true,force:true});});return {app,baseURL,client:createClient({baseURL,replay:false})};}
test('thin browser client contracts: bootstrap token, onboarding and zero-call previews',async t=>{const {app,client}=await server(t);const boot=await client.bootstrap();assert.match(boot.csrf,/^[a-f0-9]{48}$/);assert.equal(boot.replay,false);assert.equal(boot.scenarios.length,4);const d=await client.saveCampaign({campaignId:'v3-clearvault',approved:true});assert.equal(d.approved,true);const a=await client.preview({scenarioId:'cached'}),b=await client.preview({scenarioId:'offline'}),m=await client.preview({scenarioId:'mobile'});assert.equal(a.campaigns[0].retrieval.method,'vector');assert.equal(b.campaigns[0].retrieval.method,'lexical_fallback');assert.ok(m.campaigns.every(c=>!c.eligible));const r=await client.requestTurn({scenarioId:'cached'});assert.equal(r.organic.status,'waiting');await assert.rejects(client.runTurn({scenarioId:'cached'}),/organic_waiting/);assert.equal(app.service.harness.status().admitted,0);assert.equal(app.service.exchange.report().charges.length,0);});
test('HTTP exposes no organic-completion/signing/payment endpoints or private vectors',async t=>{const {baseURL,client}=await server(t);const boot=await client.bootstrap();for(const route of ['/v3/organic/complete','/v3/payment/open','/v3/freeze']){const r=await fetch(baseURL+route,{method:'POST',headers:{'x-axp-csrf':boot.csrf},body:'{}'});assert.equal(r.status,404);}const catalogue=await client.catalogue();assert.doesNotMatch(JSON.stringify(catalogue),/"(?:vector|embedding|apiKey|privateKey|wireBase64)"\s*:/);const r=await fetch(baseURL+'/v3/campaign',{method:'POST',body:'{"campaignId":"v3-clearvault","approved":true}'});assert.equal(r.status,403);});
test('client replay mode fails mutations locally with zero additional requests',async()=>{const calls=[];const client=createClient({baseURL:'http://127.0.0.1:8794',fetcher:async(url,opts)=>{calls.push({path:new URL(url).pathname,method:opts?.method??'GET'});return {ok:true,json:async()=>({replay:true,csrf:null})};}});await client.bootstrap();for(const fn of [()=>client.saveCampaign({}),()=>client.preview({}),()=>client.requestTurn({}),()=>client.runTurn({}),()=>client.render('award',{}),()=>client.fail('award',{})])await assert.rejects(fn(),/replay_read_only/);assert.deepEqual(calls,[{path:'/v3/bootstrap',method:'GET'}]);});
