import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createV3Service} from '../../packages/v3/service.mjs';
import {loadEvidence} from '../../packages/v2/evidence.mjs';
import {hash} from '../../packages/contracts/index.mjs';
import {jevResponse} from '../ml/fixtures.mjs';
const completion=r=>({turnId:r.turnId,requestId:r.requestId,inputHash:r.inputHash,agentId:'00000000-0000-0000-0000-000000000001',model:'gpt-6.1-sol',effort:'low',answer:'Fixture: compare offline signing and recovery tradeoffs; no current price claim.',completedAt:new Date().toISOString()});
function setup(t){const stateDir=mkdtempSync(join(tmpdir(),'v3-service-'));let calls=0;const s=createV3Service({stateDir,payee:'fixture-publisher',retriever:loadEvidence(),transport:p=>{calls++;return jevResponse(p,p.state.campaign.campaignId.includes('leather')?0:3,2,p.state.campaign.campaignId.includes('leather')?'no_fit':undefined);}});t.after(()=>{s.close();rmSync(stateDir,{recursive:true,force:true});});return {s,count:()=>calls};}
function approve(s){for(const d of s.state().drafts)s.saveCampaign({campaignId:d.campaign.campaignId,approved:true});}
test('onboarding creates immutable versions, freeze isolated from later laboratory edits',t=>{const {s,count}=setup(t);approve(s);const f=s.freeze(),id=f.campaigns[0].campaignId,original=hash(f);s.saveCampaign({campaignId:id,maxBidBaseUnits:'2000',status:'paused'});assert.equal(hash(s.freeze()),original);assert.equal(s.state().drafts.find(d=>d.campaign.campaignId===id).campaign.status,'paused');assert.equal(count(),0);assert.equal(s.state().exchange.charges.length,0);assert.throws(()=>s.saveCampaign({campaignId:id,budgetCapBaseUnits:'9000'}),{code:'spend_cap'});});
test('organic completion binds exact edited question and turn; waiting blocks fresh model calls',async t=>{const {s,count}=setup(t);approve(s);const input={financialMode:'synthetic',turnId:'lab-edit-one',question:'Compare offline hardware wallets for Ethereum and Solana.',mandatoryCapabilities:['crypto_storage']},r=s.requestTurn(input);await assert.rejects(s.runTurn(input),{code:'organic_waiting'});assert.equal(count(),0);assert.throws(()=>s.organic.complete({...completion(r.organic),inputHash:hash('wrong')}),{code:'organic_binding'});assert.throws(()=>s.requestTurn({...input,question:'Changed question'}),{code:'turn_conflict'});s.organic.complete(completion(r.organic));await s.runTurn(input);assert.ok(count()>0);const used=count();await s.runTurn(input);assert.equal(count(),used);assert.equal(s.state().laboratory.turns[0].organic.question,input.question);assert.equal(s.state().exchange.charges.length,0);});
test('cached and fallback retrieval are explicit, historical evidence cannot supply mobile capability',t=>{const {s}=setup(t);const a=s.preview({scenarioId:'cached'}),b=s.preview({scenarioId:'offline'}),m=s.preview({scenarioId:'mobile'});assert.equal(a.campaigns[0].retrieval.method,'vector');assert.equal(b.campaigns[0].retrieval.method,'lexical_fallback');assert.ok(m.campaigns.every(c=>!c.eligible));assert.equal(a.providerCalls,0);});
